### PR TITLE
Add `-is` & `-isnot` to type comparison operators

### LINKED ISSUE #4890: Document support for testing for `$null` using `-is` and `-isnot` in Where-Object parameter documentation as well as about_Comparison_operators
Issue Details
-----------------
[PowerShell PR #10704](https://github.com/PowerShell/PowerShell/pull/10704) adds support for testing for `$null` using `-is` and `-isnot` operators, as well as testing for `$null` using `-is` and `-isnot` parameters in `Where-Object`. For these changes, the about_Comparison_Operators documentation should be updated, as well as the documentation for the `-Is` and `-IsNot` parameters in `Where-Object`.

Also, once #4891 is merged, the about_Operators section that talks about `-is` and `-isnot` should be updated to refer to these operators in 7+ as "type or null comparison operators" instead of just "type comparison operators".

Version(s) of document impacted
------------------------------
- [X] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

### PR DESCRIPTION
**Pull request by KirkMunro**
Fixes #4890

Version(s) of document impacted
------------------------------
- [X] Impacts 7 document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by sdwheeler** [comment]
@KirkMunro You made a change to the v4 document and not the v7 document. Also, there is already a section covering the `-is` and `-isnot` operators. So you should update that section instead of adding what you did.

**Comment by sdwheeler** [comment]
@KirkMunro After further review, I am not clear on the intent of this PR. You checked all versions in the template but only update the v4 document. Are you trying to fix something in just that version? Or did you intend to document the new changes for v7?

**Comment by KirkMunro** [comment]
@sdwheeler I noticed that [about_Comparison_Operators.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md) contained details about `-is` and `-isnot`, yet the Comparison Operators section in [about_Operators](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Operators.md) does not mention those operators. My intent was to correct this so that users could find the information about those comparison operators in about_Comparison_Operators if they were reading the documentation in about_Operators.

Also, since these operators have been around since v3, I meant to fix them in versions since v3.

I clearly didn't make this change correctly, and would like to update the PR with the appropriate file changes.

Now that you pointed out that there is also about_Type_Operators.md with the `-is` and `-isnot` operators documented within it, since `-is` and `-isnot` are both about type _and_ about comparison, I think having them mentioned in both sections makes sense. This is especially the case with the forthcoming PR that allows users to use `-is` and `-isnot` to compare with `$null`.

If you agree, I'll update the other versions of the document as well so that `-is` and `-isnot` are described in the comparison operator section.

**Comment by sdwheeler** [comment]
@KirkMunro OK. I thought that was what you meant to do. Yes, please update the following:

- about_Operators [mention of type operators](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Operators.md#type-operators) as necessary for all versions.
- about_Type_Operators as necessary for all versions
- Follow up with a version 7 specific PR

Thanks.

**Comment by KirkMunro** [comment]
I have one point of clarification that is needed:

I don't believe about_Type_Operators needs any updates in this version. If you disagree, please identify the update you were referring to.

**Comment by sdwheeler** [comment]
@KirkMunro You are probably right. It will need to be updated for the v7 change for $null.

**Pull request merged**
