### PR TITLE
Adds alias notes section for *-Object cmdlets

### LINKED ISSUE #9393: 🎃 2022: Add alias notes section for the *-Object cmdlets
This issue's related to [Hacktoberfest 2022][01]. For more info, see the meta-issue below:

- MicrosoftDocs/PowerShell-Docs#9257

[01]: https://hacktoberfest.com/participation/

### Prerequisites

- [X] **Existing Issue:** Search the existing Hacktoberfest issues for this repository. If there's an issue that covers the quality area and articles you want to improve, pick a different quality area or article set. Don't file a new issue for the same work. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "🎃 2022: Command Syntax in Foo" instead of "🎃 2022: Foo"

### Quality Areas

Aliases

### Article List

- reference/./Microsoft.PowerShell.Utility/Compare-Object.md
- reference/./Microsoft.PowerShell.Utility/Group-Object.md
- reference/./Microsoft.PowerShell.Utility/Measure-Object.md
- reference/./Microsoft.PowerShell.Utility/Select-Object.md
- reference/./Microsoft.PowerShell.Utility/Sort-Object.md
- reference/./Microsoft.PowerShell.Utility/Tee-Object.md

- reference/./Microsoft.PowerShell.Core/ForEach-Object.md
- reference/./Microsoft.PowerShell.Core/Where-Object.md

### PR DESCRIPTION
**Pull request by ehmiiz**
# PR Summary

This PR adds alias notes for all the -Object cmdlets:

- reference/./Microsoft.PowerShell.Utility/Compare-Object.md
- reference/./Microsoft.PowerShell.Utility/Group-Object.md
- reference/./Microsoft.PowerShell.Utility/Measure-Object.md
- reference/./Microsoft.PowerShell.Utility/Select-Object.md
- reference/./Microsoft.PowerShell.Utility/Sort-Object.md
- reference/./Microsoft.PowerShell.Utility/Tee-Object.md
- reference/./Microsoft.PowerShell.Core/ForEach-Object.md
- reference/./Microsoft.PowerShell.Core/Where-Object.md

Fixes #9393

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
@ehmiiz Thanks so much for this submission! I'll do a review of it shortly, would you mind doing a rebase to collapse your commits down for a bit easier review?

There's a [pretty good guide][01] on interactive rebasing and [doing it in VS Code][02] is actually really nice too (that's what I tend to do these days). I'm also happy to hop on a call or something to walk you through the process if it's something you'd like to learn.

If not, I can also do the rebasing for you.

[01]: https://www.sitepoint.com/git-interactive-rebase-guide/
[02]: https://dev.to/colbygarland/using-vs-code-to-git-rebase-1lc

**Comment by ehmiiz** [comment]
Of course! 😁 Ill do a rebase next PR if thats ok

**Comment by ehmiiz** [comment]
Ah ok, makes sense
I will do it on this PR! 👍

**Comment by ehmiiz** [comment]
My idea was to close this PR and open a new one with a cleaner commit history - I'm a bit new to rebasing so this one probably got a bit messy

**Pull request closed without merging**
