### PR TITLE
Add link to online version

### PR DESCRIPTION
**Pull request by skycommand**
Version(s) of document impacted
------------------------------
- [X] Impacts 7 document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

### CODE REVIEW

**Comment by sdwheeler** [comment]
Thank you for the contribution. Unfortunately I can't accept the change for a couple of reasons.
1. The `online version` metadata value must be an FWLink URL. Those can only be created by us internally.
1. The `online version` metadata value does not apply to About topic because those help assets are published as text files and not the XML format of cmdlet help.

**Comment by skycommand** [comment]
@sdwheeler 
> 1. The `online version` metadata value must be an FWLink URL. Those can only be created by us internally.

Must? Well, currently, this page has the following link associated with it:

    http://technet.microsoft.com/library/hh847850(v=wps.630).aspx

Here is a screenshot:

Screenshot

I filed this request because that link is wrong.

> 2. The `online version` metadata value does not apply to About topic because those help assets are published as text files and not the XML format of cmdlet help.

So, its current metadata like `ms.date`, `schema` and `locale` are worthless? I did not know that. Still, since this GitHub repo is the official feedback channel for the documentation, here is mine: Please made `about_` pages accessible via the `Get-Help -online` cmdlet. It helps us, administrators, a lot. Thanks.

**Comment by sdwheeler** [comment]
@skycommand Yes, I know there are a lot of broken links. FWLinks are the current standard we are using for `online verison`. The tool to create and manage FWLink is internal to Microsoft only. I could create one and update the link in the document. However, our build pipeline is not publishing updated help CAB files for any version of PowerShell except v6. So, even if I accepted your PR, you would not benefit from the change.

This a known infrastructure issue that we want to fix. It is an issue of time, priorities, and internal dev resources to fix the pipeline. Believe me, I wish I could fix this.

**Comment by skycommand** [comment]
Ouch! So, I must probably stop issuing Update-Help on a monthly basis.

**Pull request closed without merging**
