### PR TITLE
C90810: Adding missing "releases" in brackets "[]" and new blank line after 172nd line

### PR DESCRIPTION
**Pull request by v-makoud**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.

### CODE REVIEW

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[956466d](https://github.com/v-makoud/PowerShell-Docs/pull/4413/commits/956466d6dd5cc64bac2635f84c2772fd0b1f13cc)_: 

:clock10: **Full build**: the average full build time is _11 min(s) 7 sec(s)_, this is based on the last _107_ build(s) for this repository.

**Comment by v-makoud** [comment]
#sign-off

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[956466d](https://github.com/v-makoud/PowerShell-Docs/pull/4413/commits/956466d6dd5cc64bac2635f84c2772fd0b1f13cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/v-makoud/PowerShell-Docs/blob/patch-8/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-3.0&branch=pr-en-us-4413) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-4.0&branch=pr-en-us-4413) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-5.0&branch=pr-en-us-4413) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-5.1&branch=pr-en-us-4413) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-6&branch=pr-en-us-4413) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C7%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201906071358002184-4413%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6FJlO7%2BA4ntUO6DYN%2Bl6ZQZHr0ZgmJqscbZIoXHqV3U%3D&st=2019-06-07T14%3A04%3A22Z&se=2019-07-08T14%3A09%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Neither of those changes are required. The markdown is valid and works either way. So I will merge.

**Pull request merged**
