### PR TITLE
typo: Oject -> Object

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[06bb752](https://github.com/nschonni/PowerShell-Docs/pull/3990/commits/06bb7521706701c9eae7915d0878fbcde5f91862)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[06bb752](https://github.com/nschonni/PowerShell-Docs/pull/3990/commits/06bb7521706701c9eae7915d0878fbcde5f91862)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/PowershellGet/Save-Module.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Oject/reference/5.0/PowershellGet/Save-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/powershellget/save-module?view=powershell-5.0&branch=pr-en-us-3990) (powershell-5.0) |
[reference/5.1/PowershellGet/Save-Module.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Oject/reference/5.1/PowershellGet/Save-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/powershellget/save-module?view=powershell-5.1&branch=pr-en-us-3990) (powershell-5.1) |
[reference/5.1/PowershellGet/Save-Script.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Oject/reference/5.1/PowershellGet/Save-Script.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/powershellget/save-script?view=powershell-5.1&branch=pr-en-us-3990) (powershell-5.1) |
[reference/6/PowerShellGet/Save-Module.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Oject/reference/6/PowerShellGet/Save-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/powershellget/save-module?view=powershell-6&branch=pr-en-us-3990) (powershell-6) |
[reference/6/PowerShellGet/Save-Script.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Oject/reference/6/PowerShellGet/Save-Script.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/powershellget/save-script?view=powershell-6&branch=pr-en-us-3990) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C14%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903141659564643-3990%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Bd%2FtvBRpQ5uNtRB3nSxAOCCxKT7x7xy%2B9dq5ozN9lGY%3D&st=2019-03-14T16%3A59%3A45Z&se=2019-04-14T17%3A04%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@nschonni This one is a code bug.

**Comment by nschonni** [comment]
Sounds good, i'll add an exception for cSpell then

**Pull request closed without merging**
