### PR TITLE
Document addition of wl-copy/wl-paste usage in Set/Get-Clipboard

### PR DESCRIPTION
**Pull request by helpimnotdrowning**
# PR Summary

Add note for `wl-copy`/`wl-paste` ([wl-clipboard](https://github.com/bugaevc/wl-clipboard)) dependency in Get/Set-Clipboard alongside existing `xclip` dependency for issue
- https://github.com/PowerShell/PowerShell/pull/24049

Note: In following the main Powershell [CONTRIBUTING.md](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md), I tried using `Update-MarkdownHelp` on the modified doc files, but it seemed to change far more lines than I had changed myself, so I haven't included it's changes. If I absolutely need to include those, I can.

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by helpimnotdrowning** [comment]
@microsoft-github-policy-service agree

**Comment by sdwheeler** [comment]
The clipboard cmdlets are dependent on `xclip` on Linux. They have no knowledge of the Wayland utilities. You can see this in the source code at https://github.com/PowerShell/PowerShell/blob/390a341a61642d97eafb8b309e8d4eae79d907e9/src/Microsoft.PowerShell.Commands.Management/commands/management/Clipboard.cs#L79.

**Comment by helpimnotdrowning** [comment]
Sorry, this was made to tag along with my PR in Powershell/Powershell where I add this feature: https://github.com/PowerShell/PowerShell/pull/24049 . Please re-open this PR.

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Pls do as well

**Comment by sdwheeler** [comment]
Closing this PR. The Working Groups have reviewed the code change and have suggested a different design.

**Pull request closed without merging**
