### PR TITLE
Update TOCs for new expando policy

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[323c10c](https://github.com/sdwheeler/PowerShell-Docs/pull/4096/commits/323c10c7e3d4b55f2284685ec557debb2879f3c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/.openpublishing.redirection.json) | :warning:Warning | | [Details](#user-content-10516278-e4036fdb)
[dsc/TOC.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/lnxbuiltinresources?branch=pr-en-us-4096) |
[dsc/reference/resources/builtInResource.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/builtInResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/builtinresource?branch=pr-en-us-4096) |
[dsc/reference/resources/lnxBuiltInResources.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/lnxBuiltInResources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/lnxbuiltinresources?branch=pr-en-us-4096) |
[dsc/reference/resources/windows/builtInResource.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/windows/builtInResource.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/reference/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-3.0&branch=pr-en-us-4096) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-4.0&branch=pr-en-us-4096) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-5.0&branch=pr-en-us-4096) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-5.1&branch=pr-en-us-4096) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-6&branch=pr-en-us-4096) (powershell-6) |
[wmf/TOC.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/wmf/TOC.yml) | :white_check_mark:Succeeded | |

<a id="10516278-e4036fdb"></a>
### [.openpublishing.redirection.json](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/.openpublishing.redirection.json)
 - **[Warning]** Master redirection file .openpublishing.redirection.json has a redirection rule on file &#39;dsc/reference/resources/builtInResource.md&#39;. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.
 - **[Warning]** Master redirection file .openpublishing.redirection.json has a redirection rule on file &#39;dsc/reference/resources/lnxBuiltInResources.md&#39;. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C1%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201904012149212180-4096%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lvwWIMrT%2FBOCmZEQQR6KIcIYPt1uIXM2F%2BdEylNQ4Tg%3D&st=2019-04-01T21%3A48%3A04Z&se=2019-05-02T21%3A53%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@sdwheeler For that DSC TOC, it looks like the following two nodes are "dual purpose" and needs to be fixed also:

- Pull Server > How-to guides > Register a Node with a Pull Server
- Reference > MSFT_DSCLocalConfigurationManager class

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[a78c1be](https://github.com/sdwheeler/PowerShell-Docs/pull/4096/commits/a78c1becf14460297f6c72442f6640d47433e2f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/.openpublishing.redirection.json) | :warning:Warning | | [Details](#user-content-10516278-ab5b147b)
[dsc/TOC.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/lnxbuiltinresources?branch=pr-en-us-4096) |
[dsc/reference/resources/builtInResource.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/builtInResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/builtinresource?branch=pr-en-us-4096) |
[dsc/reference/resources/lnxBuiltInResources.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/lnxBuiltInResources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/lnxbuiltinresources?branch=pr-en-us-4096) |
[dsc/reference/resources/windows/builtInResource.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/windows/builtInResource.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/reference/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-3.0&branch=pr-en-us-4096) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-4.0&branch=pr-en-us-4096) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-5.0&branch=pr-en-us-4096) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-5.1&branch=pr-en-us-4096) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-6&branch=pr-en-us-4096) (powershell-6) |
[wmf/TOC.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/wmf/TOC.yml) | :white_check_mark:Succeeded | |

<a id="10516278-ab5b147b"></a>
### [.openpublishing.redirection.json](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/.openpublishing.redirection.json)
 - **[Warning]** Master redirection file .openpublishing.redirection.json has a redirection rule on file &#39;dsc/reference/resources/builtInResource.md&#39;. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.
 - **[Warning]** Master redirection file .openpublishing.redirection.json has a redirection rule on file &#39;dsc/reference/resources/lnxBuiltInResources.md&#39;. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C1%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201904012213381644-4096%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6TtTg%2Fh4SoQF02sUqQlUUBaz%2FrR9BHQ36YyBrL63lek%3D&st=2019-04-01T22%3A13%3A13Z&se=2019-05-02T22%3A18%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[8f81103](https://github.com/sdwheeler/PowerShell-Docs/pull/4096/commits/8f8110335f10c3ccf4848148679e9a398012c1d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[dsc/TOC.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/resources/authoringresourcemofdesigner?branch=pr-en-us-4096) |
[dsc/reference/resources/linux/lnxBuiltInResources.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/linux/lnxBuiltInResources.md) | :white_check_mark:Succeeded | |
[dsc/reference/resources/windows/builtInResource.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/dsc/reference/resources/windows/builtInResource.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/reference/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-3.0&branch=pr-en-us-4096) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-4.0&branch=pr-en-us-4096) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-5.0&branch=pr-en-us-4096) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-5.1&branch=pr-en-us-4096) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/components/vscode/using-vscode?view=powershell-6&branch=pr-en-us-4096) (powershell-6) |
[wmf/TOC.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-tocfixes/wmf/TOC.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C1%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201904012224491561-4096%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YeGHxdRmBnjRkRbSmE3HsOmPzr%2FzGLfZh1MT0BCer08%3D&st=2019-04-01T22%3A23%3A40Z&se=2019-05-02T22%3A28%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
