### PR TITLE
Fixes #6664 - Updates upgrade method for macOs

### LINKED ISSUE #6664: Calling brew cask upgrade is deprecated.
# Documentation Issue
Calling brew cask upgrade is deprecated! Use brew upgrade --cask instead.

## Context of the issue

- URL to the article (Docs or GitHub URL): [Installing PowerShell on macOS](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos)
- Issue affects the following content (check all that apply):

**Conceptual content**
- [X] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

- Is the issue specific to a platform (Y/N - Win/macOS/Linux): Y - macOS

## Detailed description of the issue
The documentation instructs the user to use a deprecated command when upgrading PowerShell (both the stable release and the preview release) via Homebrew.
The documentation instructs to run `brew cask upgrade powershell`, when the user should run `brew upgrade powershell --cask`.
Likewise, for the preview release, the documentation says to run `brew cask upgrade powershell-preview`, when it should be `brew upgrade powershell-preview --cask`.

### PR DESCRIPTION
**Pull request by chasewilson**
# PR Summary
`brew cask upgrade` is deprecated and will receive an error if run. Updated to use `brew upgrade --cask`

## PR Context

Fixes #6664 
Fixes [AB#1774577](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1774577)

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [x] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [x] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by mattlinebarger** [comment]
This fixed won't work. You have, `brew upgrade --cask powershell` and `brew upgrade --cask powershell-preview`, but parameter "--cask" needs to come last. It should be `brew upgrade powershell --cask` and `brew upgrade --cask powershell-preview`.

**Comment by chasewilson** [comment]
> This fixed won't work. You have, `brew upgrade --cask powershell` and `brew upgrade --cask powershell-preview`, but parameter "--cask" needs to come last. It should be `brew upgrade powershell --cask` and `brew upgrade --cask powershell-preview`.

@mattlinebarger thanks for the feedback. I'm not getting any errors when I run the command as written. However, As powershell is already up to date it's hard to tell for sure. The command will attempt to upgrade. Is there something specific or proof you can give me to ensure we're providiing the right information?

**Comment by mattlinebarger** [comment]
I know because I tried to run it the way you have it and it didn't work. You are right, it does not generate an error, but it doesn't upgrade either. Once I changed it to have "--cask" at the end, the upgrade worked.

**Comment by chasewilson** [comment]
Thank you for letting me know, I'll update the content shortly and I'll tag you in the PR

**Comment by mattlinebarger** [comment]
Cool. Thanks for the speedy response!

**Pull request merged**
