### PR TITLE
typo: Contrl -> Control

### PR DESCRIPTION
**Pull request by nschonni**
- Cntrol -> Control

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[cc27b29](https://github.com/nschonni/PowerShell-Docs/pull/3894/commits/cc27b296df49519fffeb0d3a3be5760bad2b6da7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[developer/TOC.yml](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format?branch=pr-en-us-3894) |
[developer/format/creating-a-table-view.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/creating-a-table-view.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/creating-a-table-view?branch=pr-en-us-3894) |
[developer/format/format-schema-xml-reference.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/format-schema-xml-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/format-schema-xml-reference?branch=pr-en-us-3894) |
[developer/format/tablecolumnheader-element-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/tablecolumnheader-element-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablecolumnheader-element-format?branch=pr-en-us-3894) |
[developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format?branch=pr-en-us-3894) |
[developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format?branch=pr-en-us-3894) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C13%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903130605598769-3894%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UxTqtjFBCAMQNaBnhbA%2F5BKDDJ9pZOSZq2oxSPmb8yc%3D&st=2019-03-13T06%3A05%3A16Z&se=2019-04-13T06%3A10%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@nschonni Please resolve the conflict.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[44657e2](https://github.com/nschonni/PowerShell-Docs/pull/3894/commits/44657e2615f46c77d9e7cf5a0dcf539c0ba6f77a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[developer/TOC.yml](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format?branch=pr-en-us-3894) |
[developer/format/creating-a-table-view.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/creating-a-table-view.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/creating-a-table-view?branch=pr-en-us-3894) |
[developer/format/format-schema-xml-reference.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/format-schema-xml-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/format-schema-xml-reference?branch=pr-en-us-3894) |
[developer/format/tablecolumnheader-element-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/tablecolumnheader-element-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablecolumnheader-element-format?branch=pr-en-us-3894) |
[developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format?branch=pr-en-us-3894) |
[developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format?branch=pr-en-us-3894) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C13%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903131656169587-3894%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=64O3trR2VcF357h7WzaecWlIkR%2BNgpZGTBtuLqk1zXc%3D&st=2019-03-13T16%3A55%3A26Z&se=2019-04-13T17%3A00%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[b131dd1](https://github.com/nschonni/PowerShell-Docs/pull/3894/commits/b131dd1e8b0e682b9d80a8a67414a2a3d60a3748)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[developer/TOC.yml](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format?branch=pr-en-us-3894) |
[developer/format/creating-a-table-view.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/creating-a-table-view.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/creating-a-table-view?branch=pr-en-us-3894) |
[developer/format/format-schema-xml-reference.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/format-schema-xml-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/format-schema-xml-reference?branch=pr-en-us-3894) |
[developer/format/tablecolumnheader-element-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/tablecolumnheader-element-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablecolumnheader-element-format?branch=pr-en-us-3894) |
[developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format?branch=pr-en-us-3894) |
[developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Contrl/developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format?branch=pr-en-us-3894) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C14%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903140025295509-3894%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fa%2FIh%2BLN8HLgwlRG6p4o8xJLyqooteIg6u3aRjhtFfE%3D&st=2019-03-14T00%3A25%3A17Z&se=2019-04-14T00%3A30%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
