### PR TITLE
Rewrote the whole about_Comparison_Operators document from top to bottom

### PR DESCRIPTION
**Pull request by skycommand**
# PR Summary

**I re-wrote the `about_Comparison_Operators` completely.** As such, it would be futile to look at the diff; this new version is 99% different.

The current `about_Comparison_Operators` page suffers from several problems, some of which you can see in the screenshots below. These problems include:

1. TOC not being practically useful.
1. The first table is too long because it contains orphaned rows and empty rows.
1. Examples that confuse and make no sense, e.g. an unused function called "get-parms" (sic.)
1. Outright incorrect sentences, e.g. "Returns true when _reference value_ contained in a collection" (must be "Returns true when _test value_ contained in a collection";)
1. Out of context information snippets that are unlikely to be seen when this page is used as a reference, e.g. the implications of not using $null on the left-hand side of a comparison.

Layout problems
Example problem

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [X] Version 7.1 content
- [X] Version 7.0 content
- [X] Version 5.1 content

## PR Checklist

- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [X] PR is targeted at the _staging_ branch
- [X] All relevant versions updated
- [X] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [X] This PR is ready to merge and is not **Work in Progress**

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by skycommand** [comment]
OMG! The Microsoft Docs page changed _while_ I was filing this PR! My screenshots are taken on 10 Dec 2020, 23:21:44 (UTC).

**Comment by sdwheeler** [comment]
@skycommand Thanks for the submission. There is a lot of effort in your updates. I like a lot of the changes. I did find some typos and other issues.

Regarding your observations and feedback:

- TOC not being practically useful.
  - The TOC is autogenerated from the H2 headers. We have this problem in most of the About_ articles. I have been fixing these when we update them. Thanks for improving this.
- The first table is too long because it contains orphaned rows and empty rows.
  - The table formatting is unfortunate. It is a limitation of how About_ articles get rendered for Get-Help output. We have to split text across rows like that. We are working updates to the tools we use (Pandoc and PlatyPS) to address these limitations. So this will get fixed eventually.

Please note:
- The `## Short description` and `## Long description` headers are required by our publishing system and the PowerShell help system. So those need to be restored. 
- There was version specific information in YAML frontmatter that was overwritten when you copied the files to the other versions. 
- There are four version (5.1, 7.0, 7.1, and 7.2) - where appropriate, changes should be made in all four versions.

I am still reviewing the PR, but I will probably merge it as-is then make the necessary changes.

**Comment by skycommand** [comment]
Hello, @sdwheeler 😊

> I like a lot of the changes. I did find some typos and other issues.

Well, I'd like to know about those. I did run the file through both Microsoft Word and Grammarly, but unfortunately, there were so many false flags that I nearly cried. (For example, right now, Grammarly is telling me that this message contains the "version specific" phrase and it must be "version-specific". But since it is a typo I'm quoting, I'm not supposed to fix it.) I'm trying to develop an extension here to solve this problem, so any feedback would be great.

> The `## Short description` and `## Long description` headers are required by our publishing system and the PowerShell help system. So those need to be restored.

Oh! I thought this was a limitation of the cmdlet pages only, which need other layout elements too.

> There was version specific information in YAML frontmatter that was overwritten when you copied the files to the other versions.

Oh, you are right. I'll update the PR and fix the frontmatter in a minute.

> There are four version (5.1, 7.0, 7.1, and 7.2) - where appropriate, changes should be made in all four versions.

I've updated 5.1, 7.0, and 7.1 but I didn't act on the 7.2 pages because when I tried, Git started saying something about "rebase", "stash" and "tenanted access".

**Comment by sdwheeler** [comment]
> Well, I'd like to know about those. I did run the file through both Microsoft Word and Grammarly, but unfortunately, there were so many false flags that I nearly cried. (For example, right now, Grammarly is telling me that this message contains the "version specific" phrase and it must be "version-specific". But since it is a typo I'm quoting, I'm not supposed to fix it.) I'm trying to develop an extension here to solve this problem, so any feedback would be great.

So rather than merging the PR and then fixing the issues, I will update PR so you can see the diffs.

> I've updated 5.1, 7.0, and 7.1 but I didn't act on the 7.2 pages because when I tried, Git started saying something about "rebase", "stash" and "tenanted access".

Strange error message. I don't know what would cause that. But I should be able to handle this in my update.

**Comment by sdwheeler** [comment]
@skycommand I pushed my updates to the PR. A lot of the changes were editorial or style preferences. There were some small typos/misspellings. There were some changes I made recently that you did not have in your branch, so I added those. And there were other changes I made that were preexisting work that you didn't touch. 

Let me know if you have any questions about the changes.

**Comment by skycommand** [comment]
@sdwheeler Thanks for your time. I just finished reviewing your changes. There is a typo at 404. (It's 404... 😉) 

But I'd like to talk to you about two things that you had added back. (I had removed them deliberately.)

Line 320:
``` markdown
Unlike `-match` and `-notmatch`, these operators don't affect the `$Matches`
automatic variable.
```

And line 342:
``` markdown
If the input is a collection, the operators return the matching members of that
collection. However, the `$Matches` variable isn't populated.
```

These additions speak about the `$Matches` variable out of the appropriate context. The document does not give adequate context about `$Matches` until line 361. (Sure, there is line 70 too, but I don't bet everyone reads it.) IMHO, the second addition (line 342 and 343) should be merged into the prose at line 361. As for the first addition (line 320 and 321,) I think it is outright negative; it confuses more than it informs.

What do you think?

**Comment by skycommand** [comment]
Another problematic area is this passage, which starts at line 460:

```markdown
> [!WARNING]
> Since the `$` character is used in string expansion, you will must use
> literal strings or escape the `$` character.
>
> ```powershell
> PS> 'Hello World' -replace '(\w+) \w+', "`$1 Universe"
> Hello Universe
> ```
>
> Additionally, since the `$` character is used in substitution, you must
> escape any instances in your string.
>
> ```powershell
> PS> '5.72' -replace '(.+)', '$$$1'
> $5.72
> ```
```

There is an extra "will" at the second line, and "substitution" at line 10 needs a definite article. But the main problem is the meaning. It says "Additionally, since the `$` character is used in [the] substitution, you must escape any instances in your string." Additionally? This is just a repetition of what the first example showed, and certainly not what the second example is trying to show. The first example was about the triple syntactic role of the `$` sign, while the second is about the syntactic role of `$$` in PowerShell's flavor of Regex. In PCRE's or Golang's flavors of Regex, `$$` has no such role. See for yourself: <https://regex101.com/r/ji69aW/1>

I'm editing the text to fix this.

**Comment by skycommand** [comment]
Huh! No more strange error messages when trying to change the 7.2 document! GitLens FTW.

**Comment by sdwheeler** [comment]
@skycommand OK, I made a few more changes based on your comments. Line 404 was supposed to be deleted. Somehow I only deleted the word.  :-)  The lines about `$Matches` are important to differentiate between `-like/-notlike` and `-match/-notmatch`. I think the changes I made in this latest commit improve the context.

I appreciate the collaboration on this.

**Comment by sdwheeler** [comment]
Retrigger build

**Comment by skycommand** [comment]
@sdwheeler Thank you, and as always, it was lovely working with you.

If I didn't work with you again until the next year, merry Christmas and happy new year! 🎉

**Pull request merged**
