### PR TITLE
Fixing gallery readme inclusion

### PR DESCRIPTION
**Pull request by DCtheGeek**
Trying to fix inclusion of Gallery readme.md file.

### CODE REVIEW

**Comment by DCtheGeek** [comment]
@sdwheeler This got rid of the build error for the file, but at least in preview, it seems like it still published the readme as a page.

**Comment by victorguo** [comment]
Hi @DCtheGeek, Hi @sdwheeler,

My project has a link to https://docs.microsoft.com/en-us/powershell/gallery/readme, but today we found it was removed. Is it by any purpose?

Thanks,
Victor

**Comment by DCtheGeek** [comment]
@victorguo It was removed on purpose as it never should have been published to the web.  The [readme](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/gallery/readme.md) was informative for contributors as to the purpose of the folder, but was not intended to be published.  What was the purpose of your link to that file? The [overview](https://docs.microsoft.com/powershell/gallery) page is probably a better place to point as that's the intended landing spot for published gallery content.

**Comment by victorguo** [comment]
@DCtheGeek Thanks! I'll change the link to the [overview](https://docs.microsoft.com/powershell/gallery) page then.

**Pull request merged**
