### PR TITLE
Modify "Out-Null" Description 7.2

### PR DESCRIPTION
**Pull request by TSanzo-BLE**
Light modification to the Out-Null description.

# PR Summary

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by sdwheeler** [comment]
@TSanzo-BLE can you make the same changes to all the other versions?

**Comment by TSanzo-BLE** [comment]
@sdwheeler The modifications have been made to versions 7.3, 7.2, 7.0, and 5.1.

**Comment by michaeltlombardi** [comment]
@TSanzo-BLE - sorry to ask again, but would you mind adding those changes to _this_ PR instead of filing separate PRs? This is one logical change and keeping it scoped to a single PR makes it easier to review the commit history and follow changes in the project.

If you can add the changes from #9275, #9276, #9277, and #9278 to this PR, I think this change would be large enough to qualify for the hacktoberfest label, whereas the individual PRs I don't think quite rise to that level (and make history harder to follow). I'm going to close those PRs with a reference to this comment.

Thank you!

**Comment by TSanzo-BLE** [comment]
@michaeltlombardi I don't know how to do that.

**Comment by michaeltlombardi** [comment]
@TSanzo-BLE I'm happy to help! I can walk you through the process here in the comments or we can arrange a synchronous chat if that would be useful.

**Comment by michaeltlombardi** [comment]
I would _genuinely_ like to get these changes in, they're a definite improvement over the existing wording.

**Comment by sdwheeler** [comment]
@TSanzo-BLE This is a great opportunity to learn a new skill. See https://learn.microsoft.com/en-us/contribute/how-to-write-workflows-major

**Comment by TSanzo-BLE** [comment]
Okay, I'll give it a try maybe after work. 😄

**Comment by sdwheeler** [comment]
Replaced by https://github.com/MicrosoftDocs/PowerShell-Docs/pull/9281

**Pull request closed without merging**
