### PR TITLE
More installations methods for PowerShell 7 / Preview

### PR DESCRIPTION
**Pull request by Karl-WE**
adding 
- PSReleaseTools by Jeff Hicks
- WinGet

# PR Summary

## PR Context

Select the type(s) of documents being changed.

**Cmdlet reference & about_ topics**
- [X] Version 7.1 preview content
- [X] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

**Conceptual content**
- [ ] Fundamental conceptual articles
- [ ] Script sample articles
- [ ] DSC articles
- [ ] Gallery articles
- [ ] JEA articles
- [ ] WMF articles
- [ ] SDK articles
- [X] Community content

## PR Checklist

- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [X] PR is targeted at the _staging_ branch
- [X] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [X] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by sdwheeler** [comment]
@SteveL-MSFT @joeyaiello Do we want to document these install methods? WinGet is interesting but I'm not sure that we should recommend Jeff Hicks' module because we aren't in a position to support it.

**Comment by Karl-WE** [comment]
Sorry. I thought since the template has a community content checkbox it could be allowed.
Perhaps we can add a community content, not supported or endorsed disclaimer, I linked to his github for completeness / support. It really eases the process and requirements if winget is not yet backported. Just to get my idea.
@joeyaiello

**Comment by SteveL-MSFT** [comment]
Winget is officially supported, so we should definitely add that.  Since we already have a list of Community supported Linux distros, it seems appropriate to have a section on Community supported installers with appropriate disclaimer.  In which case, Chocolatey should also be mentioned.

**Comment by sdwheeler** [comment]
@Karl-WE I appreciate the contribution. We are discussing internally what we should include at this time. WinGet may be premature, but we do want to add it at some point. We have to be careful about third-party tools like Jeff's since we cannot support it.

The checkbox for community content is for the articles that appear in the Community section of the Table of Contents.

**Comment by joeyaiello** [comment]
Yeah, the install doc has got to pretty sacred because it's how we know you're picking up a copy that was built by us. Even if community methods *are* picking up a copy from us, we don't have eyes everywhere, and we can't guarantee that will stay the case. 

To that end, I think we can't include Chocolatey or PSReleaseTools in this doc. It's not to say that these aren't perfectly viable options for users. They're just not options that we can validate and vouch for in perpetuity.

I should also note, winget is *not* officially supported today. They're working towards support, but they have a pretty explicit disclaimer in [their documentation](https://docs.microsoft.com/en-us/windows/package-manager/): 
> Windows Package Manager and the winget tool are in public preview and may be substantially modified before they are generally available. Microsoft makes no warranties, express or implied, with respect to the information provided here.

*But*, we're already owning the package manifest for winget, it's on a path to support, and I think given a lot of the excitement around winget, it'd be more confusing *not* to mention it here.

**Comment by sdwheeler** [comment]
I made some adjustments to the PR content. We will add the winget content. Holding off on 3rd-party tools. Moved discussion to #6130.

**Comment by Karl-WE** [comment]
Thanks for merge comments and edit I am satisfied with the outcome.

**Pull request merged**
