### PR TITLE
Feature docs for reverse -split operation

### PR DESCRIPTION
**Pull request by ece-jacob-scott**
Documentation for feature (https://github.com/PowerShell/PowerShell/pull/8960).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version (6.2) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[aac6226](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3846/commits/aac62260cae743e7a0a07314dcc8db3cabd4b9d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/feature-reverse-split/reference/6/Microsoft.PowerShell.Core/About/about_Split.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_split?view=powershell-6&branch=pr-en-us-3846) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/feature-reverse-split/reference/6/Microsoft.PowerShell.Core/About/about_Split.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C11%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903112052060695-3846%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MNkI%2F1S69JqlOWmtrlqpjQwP87C2IO9X9QYi2Kn6pMw%3D&st=2019-03-11T21%3A01%3A18Z&se=2019-04-11T21%3A06%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
These are preemptive doc changes for PR (PowerShell/PowerShell#8960).

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[83af211](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3846/commits/83af211827a448329a1a2deeb02b2658ad477cac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/feature-reverse-split/reference/6/Microsoft.PowerShell.Core/About/about_Split.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_split?view=powershell-6&branch=pr-en-us-3846) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/feature-reverse-split/reference/6/Microsoft.PowerShell.Core/About/about_Split.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C11%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903112209447086-3846%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cduCarwwmA%2BACV3hVy9XFYmvNYzmacTkRt9UI49UCzA%3D&st=2019-03-11T22%3A18%3A39Z&se=2019-04-11T22%3A23%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Fixes #4396

**Pull request merged**
