### PR TITLE
adding an example to the Parameter section

### PR DESCRIPTION
**Pull request by gabrielmccoll**
I feel it gets glossed over.
Other colleagues have missed it

# PR Summary

## PR Context

Select the type(s) of documents being changed.

**Cmdlet reference & about_ topics**
- [ ] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

**Conceptual content**
- [ ] Fundamental conceptual articles
- [ ] Script sample articles
- [ ] DSC articles
- [ ] Gallery articles
- [ ] JEA articles
- [ ] WMF articles
- [ ] SDK articles
- [ ] Community content

## PR Checklist

- [ ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ ] PR has a meaningful title
- [ ] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by sdwheeler** [comment]
It is in the original spec but I can't get it to work. Investigating the use of this pattern.

**Comment by gabrielmccoll** [comment]
I just realised I didn’t try it on powershell 7.

**Comment by sdwheeler** [comment]
@gabrielmccoll Thanks for the contribution. However, after further research, the actual code doesn't support this style of comment-based help. Closing this PR and I will remove the description from the article.

**Comment by sdwheeler** [comment]
FYI - This is the preferred pattern of adding help to a parameter.

```powershell
PS> function Verb-Noun {
      [CmdletBinding()]
      param (
          [Parameter(HelpMessage='The name of the computer on which to verb the noun.')]
          [string]
          $Computername
      )

      "Verbing the noun on $Computername"
  }

PS> get-help Verb-Noun -full

NAME
    Verb-Noun

SYNTAX
    Verb-Noun [[-Computername] <string>] [<CommonParameters>]


PARAMETERS
    -Computername <string>
        The name of the computer on which to verb the noun.

        Required?                    false
        Position?                    0
        Accept pipeline input?       false
        Parameter set name           (All)
        Aliases                      None
        Dynamic?                     false

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).


INPUTS
    None


OUTPUTS
    System.Object

ALIASES
    None


REMARKS
    None
```

**Comment by gabrielmccoll** [comment]
That’s different from adding to comment based help like what I’ve shown though.   
That’s what shows up for mandatory parameters if you don’t include them 


https://powershell.org/2013/05/a-helpful-message-about-helpmessage/

**Comment by gabrielmccoll** [comment]
Are you remembering to do get-help function -full

**Comment by gabrielmccoll** [comment]
powershellexamplesean

Here's an example of it working. it works in 5.1 and 7.0 I have now checked.  So please don't remove it from the documentation as it works and is clear. Parameter HelpMessage isn't the same thing and doesn't add to comment based help.

**Comment by sdwheeler** [comment]
OK, I recreated your example. It does work but only if you use it with at least one comment-based help directive (like .SYNOPSIS). If you have no other help then the parameter comments are not used. That is what I was seeing in my tests.

I will adjust to docs accordingly.

Also `[Parameter(HelpMessage='help message text.')]` does show up in `Get-Help -Full`.

**Comment by gabrielmccoll** [comment]
Ah nice one. I hadn’t tried it but had read it didn’t work. Thanks for the new info

**Comment by gabrielmccoll** [comment]
Any chance you can reopen the pull and I’ll amend it. Get my wee picture up for efforts haha

**Comment by gabrielmccoll** [comment]
Actually it looks like that way that is the preferred way to add help message you've shown me only works if there's no other help on the function.  Why is it the preferred way ?

seanhelpparam
seanhelpparam2

**Comment by sdwheeler** [comment]
I am sorry for the confusion around this contribution. I do appreciate contributions like this. I tested your original submission and even worked with our Dev team to debug it and we couldn't get it to work. We were missing the information about needing at least one other help keyword.

I have a PR to add the information you wanted for the comment-base help. I clarified the requirement needing at least one Help keyword and did some other editorial clean up. Updates like this need to be made to all 4 versions of the article. 

It's an interesting find that HelpMessage can't be used with comment-based help that way. That's new information. We could add this new information about HelpMessage and comment-based help. Do you want to submit a PR to add that information?

**Pull request closed without merging**
