### PR TITLE
invalid character in examples

### PR DESCRIPTION
**Pull request by mgreenegit**
hyphen/dash

### CODE REVIEW

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[f01045f](https://github.com/mgreenegit/PowerShell-Docs/pull/4100/commits/f01045fb2d1223769536a12a0e88cbc963ce174b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/reference/resources/windows/scriptResource.md](https://github.com/mgreenegit/PowerShell-Docs/blob/patch-3/dsc/reference/resources/windows/scriptResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/windows/scriptresource?branch=pr-en-us-4100) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201904021536463857-4100%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WQZ5S00XomcM9IXlUegPS8BqCbO5%2F5JErVyYb2I7%2FwQ%3D&st=2019-04-02T15%3A35%3A55Z&se=2019-05-03T15%3A40%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mgreenegit** [comment]
#sign-off

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[9b2aac6](https://github.com/mgreenegit/PowerShell-Docs/pull/4100/commits/9b2aac60d60499a5b8fb038bf145d45ba433a920)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/reference/resources/windows/scriptResource.md](https://github.com/mgreenegit/PowerShell-Docs/blob/patch-3/dsc/reference/resources/windows/scriptResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/resources/windows/scriptresource?branch=pr-en-us-4100) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201904021550044420-4100%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=F4EIQofrJIHL5I8N0LdVxu%2FYS5RSN5ZLj0IIkTlXxqM%3D&st=2019-04-02T15%3A49%3A16Z&se=2019-05-03T15%3A54%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mgreenegit** [comment]
@sign-off

**Pull request merged**
