### PR TITLE
🎃 Add aliases to Notes section for *-Alias cmdlets

### PR DESCRIPTION
**Pull request by ehmiiz**
# PR Summary

Edit: Initial PR was only for New-Alias but decided to implement for *-Alias

Adding alias documentation for the *-Alias Cmdlet
My collective issue (hopefully this is ok) #9345 

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by ehmiiz** [comment]
This PR is my initial request to contribute to Hacktoberfest 2022 #9257
My collective issue (hopefully this is ok) #9345
Feedback is very much appreciated!

**Review by michaeltlombardi — CHANGES_REQUESTED** [review]
@ehmiiz thanks so much for submitting this PR and helping out during Hacktoberfest! I notice in your issue you specify only targeting the Windows PowerShell `*-Alias` cmdlets. Are you open to picking up the other versions in this PR?

The only technical change I see that needs to be made to the files you've submitted is to update the [ms.date][01] key in the frontmatter for the page to reflect today's date - this lets folks know when a document was last modified.

[01]: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/9344/files#diff-05a0616665e85c152ea66447db821db23954e95804ac3f585b129cd94955c848R5

**Comment by ehmiiz** [comment]
> @ehmiiz thanks so much for submitting this PR and helping out during Hacktoberfest! I notice in your issue you specify only targeting the Windows PowerShell `*-Alias` cmdlets. Are you open to picking up the other versions in this PR?
> 
> The only technical change I see that needs to be made to the files you've submitted is to update the [ms.date](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/9344/files#diff-05a0616665e85c152ea66447db821db23954e95804ac3f585b129cd94955c848R5) key in the frontmatter for the page to reflect today's date - this lets folks know when a document was last modified.

Thanks for the push in the right direction. Added for all version with the new commit, updated ms.date as well.

**Review by michaeltlombardi — COMMENTED** [review]
It looks like all your changes landed and are good except for the `ms.date` update on the 5.1 files, it doesn't seem those came through. Once that's in place, I'm happy to approve and merge!

**Pull request merged**
