### PR TITLE
Fixes #7096 - update gotchas for classes

### LINKED ISSUE #7096: Please document the issues encountered when working with classes particularly inside modules
Please document the following issues

- the read only nature of class definitions and the implications this has
- what are the available work arounds both in a powershell session and in VSCode
- when can "import module" be used and when can using module be used and the pros and cons of each
- document the inexplicable errors that currently make no sense to the user:
eg a message like this:

> Cannot process argument transformation on parameter ...... Cannot convert the "CosmosDbDatabase" value of type "CosmosDbDatabase" to type "CosmosDbDatabase".

really doesn't make any sense, until you know what the problem actually is (this is caused by the read only nature of classes).
- what difference it makes when a class is defined and meant to be used external to the module as opposed to a class that is internal only.
- best practices to employ when using classes including when you're using modules
- if you import a module in your profile and that module is one that you're currently working on and rebuilding, then the import in the profile should be removed. Please explain why this is so

I've taken to defining a separate class module that can be used by client modules purely to get around the issue of being able to access class types properly. I don't know if this is wise, but it does resolve some of these isses, but creates more friction as now functionality that should be bundled together are now separated by module borders.

All this information should be documented in Microsoft docs. Users shouldnt have to read 3rd party blog sites for this fundamental information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcd71bfb-1b7a-f31b-f618-d12823b84c3f
* Version Independent ID: a5651d52-5618-47e4-67df-6191278f0ad5
* Content: [about_Classes - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7.1)
* Content Source: [reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md)
* Product: **powershell**
* Technology: **powershell-conceptual**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

### PR DESCRIPTION
**Pull request by sdwheeler**
# PR Summary

Fixes [AB#1809059](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809059) - Fixes #7096 - update gotchas for classes

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [x] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Review by chasewilson — APPROVED** [review]

**Comment by plastikfan** [comment]
The issue I raise about missing information about using classes has been closed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7096 in favour of this one.

However, I am concerned the many of the points raised in my issue are not reflected in the updated documentation. The most important and difficult characteristics of classes is that once a class is defined in a session generally it can't be updated by redefining it in the same way functions are. The only way to resolve these types of problems is the drop the current session and start fresh. I was stuck on these types of problems for weeks because its not documented. Please make sure there is a comprehensive explanation of this aspect in the updated docs, because even though I know that sometimes a restart is the only thing that can fix a re-defined class, I still don't fully understand the finer details, because it's not documented.

**Comment by plastikfan** [comment]
The issue I raise about missing information about using classes has been closed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7096 in favour of this one.

However, I am concerned the many of the points raised in my issue are not reflected in the updated documentation. The most important and difficult characteristics of classes is that once a class is defined in a session generally it can't be updated by redefining it in the same way functions are. The only way to resolve these types of problems is the drop the current session and start fresh. I was stuck on these types of problems for weeks because its not documented. Please make sure there is a comprehensive explanation of this aspect in the updated docs, because even though I know that sometimes a restart is the only thing that can fix a re-defined class, I still don't fully understand the finer details, because it's not documented.

The about using doesnt take into account a common pattern for module development. There needs to be an example that reflects this, otherwise there is a glaring hole which is misleading. At the moment, there is nothing that describes how to access a class definition which is in a different file in the same module. This isn't possible, but this has not been accounted for in about classes and about using. A common pattern for module development is to use separate files for separate functions and classes (which go into folders Classes, Public, Internal). Now Im not expecting this pattern to be documented. What I do expect though is for the document to CLEARLY shutdown the notion that classes can be accesses from 1 file to another. The using statement is not applicable in this circumstance. It is only useful when accessing classes in a separate module. Please emphasis this, because its really important. I would not have wasted weeks in development time on my own projects if I had known this.

**Comment by sdwheeler** [comment]
@plastikfan Ah, I will add a note about the why you can't redefine classes without restarting the session.

Also, I am getting more input from the dev team to answer some of these questions.

**Comment by plastikfan** [comment]
Ok @sdwheeler, I'll look forward to more information. Thanks for your efforts in this regard

**Comment by sdwheeler** [comment]
@plastikfan You an avoid creating a new session after redefining a class. But you must use `Remove-Module` to remove the current version from the session. Then use `Import-Module` and `using module` to load the new version. Just re-importing the module does reload the submodules (see https://github.com/PowerShell/PowerShell/issues/2505). You must use `Remove-Module` first.

**Comment by plastikfan** [comment]
Ok, my test cases already use remove-module and then re-import using a full path and I still suffered these problems. I'll need to take another look, but my initial thought is that's not the whole story. Weeks of frustration attest to that

**Comment by sdwheeler** [comment]
As to the question about your module development pattern:

You should be able to define you classes in a one file (a module.PSM1 file) the put `using module <path>` in the files containing your functions.  If you are still having problems getting that to work or using `Remove-Module`/`Import-Module`,  then, please file an issue in the [Source code repo](https://aka.ms/psfeedback). They are better able to help you there.

**Pull request merged**
