### PR TITLE
Update Get-Unique.md

### PR DESCRIPTION
**Pull request by guyisit**
Since the command has static input/output, showing the output I think helps quickly visualize and understand the function. Other docs examples show the output in this instance, too.

Version(s) of document impacted
------------------------------
- [ ] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[da087fb](https://github.com/guyisit/PowerShell-Docs/pull/4409/commits/da087fbb93076c87fad93eb3bc8e306750207775)_: 

:clock10: **Full build**: the average full build time is _11 min(s) 18 sec(s)_, this is based on the last _104_ build(s) for this repository.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[da087fb](https://github.com/guyisit/PowerShell-Docs/pull/4409/commits/da087fbb93076c87fad93eb3bc8e306750207775)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Get-Unique.md](https://github.com/guyisit/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Utility/Get-Unique.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/get-unique?view=powershell-6&branch=pr-en-us-4409) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C6%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201906061757175409-4409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1D7OUGtrcCZt43In2KdPq5BjagELILJOq2nbgeexScg%3D&st=2019-06-06T18%3A03%3A43Z&se=2019-07-07T18%3A08%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[394667a](https://github.com/guyisit/PowerShell-Docs/pull/4409/commits/394667adc8e176890f0418917dbd25b2141c07bd)_: 

:clock10: **Full build**: the average full build time is _11 min(s) 10 sec(s)_, this is based on the last _105_ build(s) for this repository.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[394667a](https://github.com/guyisit/PowerShell-Docs/pull/4409/commits/394667adc8e176890f0418917dbd25b2141c07bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Get-Unique.md](https://github.com/guyisit/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Utility/Get-Unique.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/get-unique?view=powershell-3.0&branch=pr-en-us-4409) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Utility/Get-Unique.md](https://github.com/guyisit/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Utility/Get-Unique.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/get-unique?view=powershell-4.0&branch=pr-en-us-4409) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Utility/Get-Unique.md](https://github.com/guyisit/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Utility/Get-Unique.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/get-unique?view=powershell-5.0&branch=pr-en-us-4409) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Utility/Get-Unique.md](https://github.com/guyisit/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-Unique.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/get-unique?view=powershell-5.1&branch=pr-en-us-4409) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Utility/Get-Unique.md](https://github.com/guyisit/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Utility/Get-Unique.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/get-unique?view=powershell-6&branch=pr-en-us-4409) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C6%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201906061910530893-4409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IsWYVs11Iz7xuRw%2B2bHo41R4VhhgJ0RjaZftuPczY9o%3D&st=2019-06-06T19%3A16%3A59Z&se=2019-07-07T19%3A21%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@guyisit Thanks for the contribution. Please sign the CLA. This is required before I can accept the change. Also, in future, please update all versions of the document (as appropriate). I updated your PR to include those other versions.

**Comment by guyisit** [comment]
Thanks, Sean. I missed all the emails originally.
Also, good to know about the PR- I appreciate you taking the time to inform me on that.

**Pull request merged**
