### PR TITLE
Updating TOC for new document

### PR DESCRIPTION
**Pull request by bobbytreed**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 55 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/TOC.yml](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbyreed-TOCupdate/dsc/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-performrequiredconfigurationchecks?branch=pr-en-us-3621) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901291824283115-3621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=i0YvuByfers3WTMobIgGpdI2%2F8umm%2BHcWb0UxVkC9iY%3D&st=2019-01-29T18%3A32%3A59Z&se=2019-03-01T18%3A37%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
This change has already been made. Closing the PR.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 54 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ea5a287](https://github.com/bobbytreed/PowerShell-Docs/pull/3621/commits/ea5a2870a9c2e26b16998edfa561d664d8cbfb7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/TOC.yml](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbyreed-TOCupdate/dsc/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-performrequiredconfigurationchecks?branch=pr-en-us-3621) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901291856359306-3621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gJrSksNk2JEn3cHbvx%2BJayMZ6GYHWqQv4A3bqknWKMk%3D&st=2019-01-29T19%3A06%3A44Z&se=2019-03-01T19%3A11%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
