### PR TITLE
Fixes #11493 - Continuation of PR11493 - copy changes to other versions

### PR DESCRIPTION
**Pull request by sdwheeler**
# PR Summary

Continuation of PR11493 - copy changes to other versions

- Fixes [AB#334889](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/334889)
- Fixes #11493

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by sdwheeler** [comment]
@ArieHein FYI

**Review by michaeltlombardi — APPROVED** [review]

**Comment by ArieHein** [comment]
> @ArieHein FYI

Thanks for the heads up. Was planning to do one folder at a time, to also reduce the amount of review you guys and gals are doing :)

**Comment by sdwheeler** [comment]
No worries. Small changes like that can be done in bulk. We use [Beyond Compare](https://www.scootersoftware.com/) to copy changes across the versions. So updating the other versions is quick and easy.

**Comment by ArieHein** [comment]
@sdwheeler I have more fixes but this time to Markdown rules. Problem is one of your rules in the mardownlint is MD012 that requires empty lines after headers. Just in the 5.1 sub folder, there are over 400 files that have that issue, as you can see:
So you want a PR with so many fixes (it fixes more MD rules that are not complying with the markdownlint rules)

image

**Comment by sdwheeler** [comment]
@ArieHein There is one exception to MD012. We don't put a blank line after `## SYNOPSIS` due to a bug in the publishing tool chain. We are working to fix that bug, but we are still months away before we can release it.

If there are occurrences in other places besides `## SYNOPSIS`, then those can be fixed. With the one exception, these are the rules we want to enforce:

```
id    aliases                  description
--    -------                  -----------
MD012 {no-multiple-blanks}     Multiple consecutive blank lines
MD022 {blanks-around-headings} Headings should be surrounded by blank lines
MD031 {blanks-around-fences}   Fenced code blocks should be surrounded by blank lines
MD032 {blanks-around-lists}    Lists should be surrounded by blank lines
MD058 {blanks-around-tables}   Tables should be surrounded by blank lines
```

If you want to submit bulk updates, limit them to one folder per PR. And limit the change to fixing the blank lines. That will be easy to review.

**Comment by ArieHein** [comment]
That makes sense, this will probably decrease the number dramatically.

thanks for the headsup.

ill do it for the 7.4 and 7.5 as well as ive seen the issue to remove 7.2 folders

**Pull request merged**
