### PR TITLE
Rewrite Credentials in DSC for clarity

### PR DESCRIPTION
**Pull request by bobbytreed**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[dcf3853](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/dcf38532e3e870282f4993231fa119d855e07126)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[dcf3853](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/dcf38532e3e870282f4993231fa119d855e07126)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[dcf3853](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/dcf38532e3e870282f4993231fa119d855e07126)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 57 sec(s)_

**Comment by sdwheeler** [comment]
@bobbytreed  LGTM

@mgreenegit Waiting on your review.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e69d232](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/e69d2322354ea9bf2e752a91cc1fe5809ba314f8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e69d232](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/e69d2322354ea9bf2e752a91cc1fe5809ba314f8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e69d232](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/e69d2322354ea9bf2e752a91cc1fe5809ba314f8)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 57 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e69d232](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/e69d2322354ea9bf2e752a91cc1fe5809ba314f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/configurations/configDataCredentials.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbyreed-issue3384/dsc/configurations/configDataCredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/configurations/configdatacredentials?branch=pr-en-us-3630) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C31%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901311643511797-3630%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YnB7lltohBDbkG%2B5aXBrqmkuCPuMRnJ9nACITMbI02c%3D&st=2019-01-31T16%3A52%3A40Z&se=2019-03-03T16%3A57%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c7dfd5e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/c7dfd5e6b8f6abe342aadbdcc65b9ff93e91d9db)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c7dfd5e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/c7dfd5e6b8f6abe342aadbdcc65b9ff93e91d9db)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c7dfd5e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/c7dfd5e6b8f6abe342aadbdcc65b9ff93e91d9db)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 56 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c7dfd5e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/c7dfd5e6b8f6abe342aadbdcc65b9ff93e91d9db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/configurations/configDataCredentials.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbyreed-issue3384/dsc/configurations/configDataCredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/configurations/configdatacredentials?branch=pr-en-us-3630) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C31%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901311757283378-3630%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Smw8022Yn2y9pIxy9BsSzzXE1s2FgzMSC%2FFon5nPVS4%3D&st=2019-01-31T18%3A06%3A27Z&se=2019-03-03T18%3A11%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[408d38e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/408d38e3b34a1959ecbd91937742d98715b2e376)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[408d38e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/408d38e3b34a1959ecbd91937742d98715b2e376)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[408d38e](https://github.com/bobbytreed/PowerShell-Docs/pull/3630/commits/408d38e3b34a1959ecbd91937742d98715b2e376)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 55 sec(s)_

**Comment by mgreenegit** [comment]
Thank you!!!

**Pull request merged**
