### PR TITLE
Fixes #3719 - Repair Bad XML and format articles.

### LINKED ISSUE #3719: A header too many
In this example there is a &lt;TableColumnHeader/&gt; too much

&lt;View&gt;
  &lt;Name&gt;System.Globalization.CultureInfo&lt;/Name&gt;
  &lt;ViewSelectedBy&gt;
    &lt;TypeName&gt;Deserialized.System.Globalization.CultureInfo&lt;/TypeName&gt;
    &lt;TypeName&gt;System.Globalization.CultureInfo&lt;/TypeName&gt;
  &lt;/ViewSelectedBy&gt;
  &lt;TableControl&gt;
    &lt;TableHeaders&gt;
      &lt;TableColumnHeader&gt;
        &lt;Width&gt;16&lt;/Width&gt;
      &lt;/TableColumnHeader&gt;
      &lt;TableColumnHeader&gt;
        &lt;Width&gt;16&lt;/Width&gt;
      &lt;/TableColumnHeader&gt;
      &lt;TableColumnHeader/&gt;
    &lt;/TableHeaders&gt;
    &lt;TableRowEntries&gt;
      &lt;TableRowEntry&gt;
        &lt;TableColumnItems&gt;
          &lt;TableColumnItem&gt;
            &lt;PropertyName&gt;LCID&lt;/PropertyName&gt;
          &lt;/TableColumnItem&gt;
          &lt;TableColumnItem&gt;
            &lt;PropertyName&gt;Name&lt;/PropertyName&gt;
          &lt;/TableColumnItem&gt;
          &lt;TableColumnItem&gt;
            &lt;PropertyName&gt;DisplayName&lt;/PropertyName&gt;
          &lt;/TableColumnItem&gt;
        &lt;/TableColumnItems&gt;
      &lt;/TableRowEntry&gt;
    &lt;/TableRowEntries&gt;
  &lt;/TableControl&gt;
&lt;/View&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5d7800-2767-085a-e901-c9c85bd60111
* Version Independent ID: e363027f-b76b-edbb-22dc-02d5924cfcb9
* Content: [about_Format.ps1xml](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

### PR DESCRIPTION
**Pull request by bobbytreed**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1fe539c](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/1fe539cf6cfacf2f1da60681c6c95a28f9149b0f)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1fe539c](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/1fe539cf6cfacf2f1da60681c6c95a28f9149b0f)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 47 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1fe539c](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/1fe539cf6cfacf2f1da60681c6c95a28f9149b0f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-3.0&branch=pr-en-us-3734) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-4.0&branch=pr-en-us-3734) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.0&branch=pr-en-us-3734) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.1&branch=pr-en-us-3734) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6&branch=pr-en-us-3734) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[MyDotNetTypes.Format.ps1xml](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/MyDotNetTypes.Format.ps1xml) | :white_check_mark:Succeeded | |

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C19%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902191830363110-3734%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mAx2wB%2BhuPrynL7NTHPWedrKrhxoaOJXt%2FB9EmL8hAI%3D&st=2019-02-19T18%3A41%3A52Z&se=2019-03-22T18%3A46%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[63ff666](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/63ff6667f2ff7775754b6c550e3b4833aff2ea1d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[63ff666](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/63ff6667f2ff7775754b6c550e3b4833aff2ea1d)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by salih27** [comment]
Evet. 


⁣Android için BlueMail uygulamasını edinin ​

On 19 Şub 2019 21:49 , at 21:49 , Sean Wheeler <notifications@github.com> yazdı:

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[63ff666](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/63ff6667f2ff7775754b6c550e3b4833aff2ea1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-3.0&branch=pr-en-us-3734) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-4.0&branch=pr-en-us-3734) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.0&branch=pr-en-us-3734) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.1&branch=pr-en-us-3734) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6&branch=pr-en-us-3734) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C19%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902191831050329-3734%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=M8wl%2BW0asxGhJip0CkvbgOLm5GzSCWMpM2W1W4X%2F3v0%3D&st=2019-02-19T18%3A56%3A58Z&se=2019-03-22T19%3A01%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[67ef778](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/67ef7782b257ca3835d5227e8e8249653cfec188)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[67ef778](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/67ef7782b257ca3835d5227e8e8249653cfec188)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[67ef778](https://github.com/bobbytreed/PowerShell-Docs/pull/3734/commits/67ef7782b257ca3835d5227e8e8249653cfec188)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-3.0&branch=pr-en-us-3734) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-4.0&branch=pr-en-us-3734) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.0&branch=pr-en-us-3734) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.1&branch=pr-en-us-3734) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6&branch=pr-en-us-3734) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbytreed-issue3719/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C19%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902191847417310-3734%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R%2Bg2da6Q3fy%2FyL7ym3cywD85o%2FUvW1YA%2F47tL2%2F1I28%3D&st=2019-02-19T19%3A12%3A03Z&se=2019-03-22T19%3A17%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
