### PR TITLE
Fix formatting issues in get-ciminstance for version 6

### PR DESCRIPTION
**Pull request by FISHMANPET**
I tried to fix the formatting errors without changing any of the content.  While I was there I also modified the file to be compatible with markdown formatting standards

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [x] This PR partially fixes the issue, and issue #3749 tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1ad6dae](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/1ad6daea4c9363475f175e6554158b549e93740e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1ad6dae](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/1ad6daea4c9363475f175e6554158b549e93740e)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1ad6dae](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/1ad6daea4c9363475f175e6554158b549e93740e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/CimCmdlets/Get-CimInstance.md](https://github.com/FISHMANPET/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Get-CimInstance.md) | :x:Error | | [Details](#user-content-reference%2F6%2FCimCmdlets%2FGet-CimInstance.md)

<a name="reference%2F6%2FCimCmdlets%2FGet-CimInstance.md"></a>
### [reference/6/CimCmdlets/Get-CimInstance.md](https://github.com/FISHMANPET/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Get-CimInstance.md)
 - **[Error]** Unable to load file &#39;6/CimCmdlets/Get-CimInstance.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :138:(365) &#39;```
PS C:\&gt;Get-CimInstance -CimInstance $x
```
...&#39;
 Expect Heading

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C21%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902212134341943-3750%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SfFHFYQ9t6O%2FPZFXedpESKJr4OW0xiWmELTAMt4CsHo%3D&st=2019-02-21T21%3A42%3A48Z&se=2019-03-24T21%3A47%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[7e514e4](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/7e514e4b284ca6d880d4e9ff5c09377efdd3de6c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[7e514e4](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/7e514e4b284ca6d880d4e9ff5c09377efdd3de6c)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[7e514e4](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/7e514e4b284ca6d880d4e9ff5c09377efdd3de6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/CimCmdlets/Get-CimInstance.md](https://github.com/FISHMANPET/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Get-CimInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/cimcmdlets/get-ciminstance?view=powershell-6&branch=pr-en-us-3750) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C21%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902212204474439-3750%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9jcrUS0IobgH9h65bgZstxj4RUF0gAxtihXexU1VuR4%3D&st=2019-02-21T22%3A13%3A41Z&se=2019-03-24T22%3A18%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1e0ccd2](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/1e0ccd2c54923d4a8faa0648a0fe732671489574)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1e0ccd2](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/1e0ccd2c54923d4a8faa0648a0fe732671489574)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by sdwheeler** [comment]
I appreciate the PR and will accept as soon as the build finishes. However, there are a lot of other formatting changes that need to be made. Please read our [contributor guide](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/CONTRIBUTING.md). Also, the new standard for list items that wrap is to line up the wrapped lines with the first character after the bullet.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1e0ccd2](https://github.com/FISHMANPET/PowerShell-Docs/pull/3750/commits/1e0ccd2c54923d4a8faa0648a0fe732671489574)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/CimCmdlets/Get-CimInstance.md](https://github.com/FISHMANPET/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/Get-CimInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/cimcmdlets/get-ciminstance?view=powershell-6&branch=pr-en-us-3750) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C21%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902212247307837-3750%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3ksrZPOUfjB69zIA1Z0rrqc%2Fe%2F1BmHRz9xXvUdWMO40%3D&st=2019-02-21T22%3A57%3A15Z&se=2019-03-24T23%3A02%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by salih27** [comment]
⁣Android için BlueMail uygulamasını edinin ​

On 22 Şub 2019 01:49 , at 01:49 , Zachary Alexander <notifications@github.com> yazdı:

**Pull request merged**
