### PR TITLE
Get-Item -stream now works on directories. (PS #13941)

### PR DESCRIPTION
**Pull request by kyanha**
# PR Summary

Modified for Powershell 7.1 (but is actually related to Powershell 7.2, since the PR didn't get into Powershell for 7.1), relates to Powershell/Powershell#13941, to document Get-Item -stream now working for directories.

[PowerShell Pull Request](https://github.com/PowerShell/PowerShell/pull/13941)

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [X] Version 7.1 preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

## PR Checklist

- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [X] PR is targeted at the _staging_ branch
- [X] All relevant versions updated
- [X] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [X] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by kyanha** [comment]
Updated the PR that this should be waiting on, now PowerShell/Powershell#13941.

**Comment by sdwheeler** [comment]
@kyanha Your code PR has been merged. But the change affects more than just `Get-Item`. Can you update the docs for the other cmdlets.

**Comment by kyanha** [comment]
None of the documentation for the other cmdlets involved stated that -Stream could only target files, not directories.  Get-Content was the only one that did.  Accordingly, I didn't think that any changes were necessary for the remaining documentation to be correct.

I have updated all six with the version changelog.  Note that the -Stream parameter isn't even recognized on non-Windows systems.

Note that PR PowerShell/13941 was accepted into PowerShell 7.2, not 7.1.  I'm not sure what to do about that, since there is no `reference/7.2` directory.

**Comment by chasewilson** [comment]
Hey @kyanha, with the release of PowerShell 7.2, Sean added the files for 7.2. Have you rebased in the last bit?

**Comment by kyanha** [comment]
I did a git fetch and git pull from origin last night, and I didn't get any
updates. When did these changes happen?

**Comment by chasewilson** [comment]
A while back. You might need to run the following:
```cmd
git checkout staging
git fetch upstream staging
git pull upsteram staging
git checkout kyanha:ps10570
git rebase staging
```

This might be a bit overkill but I do it just to keep all my stuff current every once in a while. 

The origin branch is just your forked repo and needs to be rebased (synced) with the history of the Upstream (Microsoft Docs) repo. 

Let me know if you have any issues with this

**Comment by kyanha** [comment]
I'm trying, and I can't figure out the git commands to make it happen. I'm giving up on doing so. I'm certain you have more knowledge, capacity, and patience to fight with this than I do, particularly since you're actually getting paid to do this.

I've fought for over two months now to get this completed and landed, and I don't have the patience anymore.

**Comment by chasewilson** [comment]
@kyanha I'm sorry you are frustrated. I'll go ahead and create a new PR if you don't mind then and link and credit you in there if you don't have an issue with that course of action? 

The contribution is really appreciated and I'm sorry the process has been a struggle. If you have any questions or want to go through the git process some, let me know. I know how confusing it can be and have been on the frustrating end of things more than once.

**Comment by chasewilson** [comment]
Going to close this PR due to finishing it [here](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/7064). 

Thanks again!

**Pull request closed without merging**
