### PR TITLE
Removed typo

### PR DESCRIPTION
**Pull request by asadrefai**
Removed extra [ (brackets)

# PR Summary

## PR Checklist

- [ ] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [ ] **Summary:** This PR's summary describes the scope and intent of the change.
- [ ] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [ ] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by sdwheeler** [comment]
@asadrefai Thanks for your submission, but those brackets are correct. Those are syntax diagrams. They brackets indicate that the second parameters are optional. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_command_syntax for an explanation of how to read the syntax diagrams.

**Comment by asadrefai** [comment]
Ah I see. Thank you @sdwheeler

**Comment by asadrefai** [comment]
@sdwheeler may be the opening [ brackets can be placed after comma ','?

**Comment by sdwheeler** [comment]
No the comma is only needed if you have more parameters. So it needs to be inside the brackets.

**Pull request closed without merging**
