### PR TITLE
Remove Asterisks from class names in links

### PR DESCRIPTION
**Pull request by nschonni**
Doesn't remove them all, but took separate commits for the different find/replaces. Ref #3903

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c4646c6](https://github.com/nschonni/PowerShell-Docs/pull/3904/commits/c4646c6cb0871e00ec2d5be4d848a0f8d03b0ed9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/PowerShell-Docs, working directory: W:\no1d-s, target branch: staging, target branch commit: b9b5ec680a1c8867e22aeee21b18d3cecaec0c1f, source branch: fd58386580d7199a66bcf38fdc44d0e4/typo-Stopprocessing-, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C13%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903131716574884-3904%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=utd%2B3P2s4Zn%2B7P01ssFDwwMoVfzKoKuGZpdkYWltNxs%3D&st=2019-03-13T17%3A12%3A33Z&se=2019-04-13T17%3A17%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@nschonni Please resolve the conflicts.

**Comment by nschonni** [comment]
@sdwheeler I'll rebase later tonight. Do you want me to keep pushing the other trailing asterisk replacements to this one PR, or do you prefer separate ones?

**Comment by sdwheeler** [comment]
@nschonni Separate, please. Thanks.

**Comment by nschonni** [comment]
Will do, I can break this one up if you prefer. I think there was just one or two that were on the same line that were easier to put together to avoid a merge conflict

**Comment by sdwheeler** [comment]
@nschonni Just keep it under 50 files at a time in a PR. Thanks

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9f8e944](https://github.com/nschonni/PowerShell-Docs/pull/3904/commits/9f8e944fa73de7c25ea16e8f7d799d6bba3e5ccb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/cmdlet/adding-aliases-wildcard-expansion-and-help-to-cmdlet-parameters.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/adding-aliases-wildcard-expansion-and-help-to-cmdlet-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/adding-aliases-wildcard-expansion-and-help-to-cmdlet-parameters?branch=pr-en-us-3904) |
[developer/cmdlet/adding-non-terminating-error-reporting-to-your-cmdlet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/adding-non-terminating-error-reporting-to-your-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/adding-non-terminating-error-reporting-to-your-cmdlet?branch=pr-en-us-3904) |
[developer/cmdlet/adding-parameter-sets-to-a-cmdlet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/adding-parameter-sets-to-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/adding-parameter-sets-to-a-cmdlet?branch=pr-en-us-3904) |
[developer/cmdlet/adding-parameters-that-process-command-line-input.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/adding-parameters-that-process-command-line-input.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/adding-parameters-that-process-command-line-input?branch=pr-en-us-3904) |
[developer/cmdlet/adding-parameters-that-process-pipeline-input.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/adding-parameters-that-process-pipeline-input.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/adding-parameters-that-process-pipeline-input?branch=pr-en-us-3904) |
[developer/cmdlet/adding-user-messages-to-your-cmdlet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/adding-user-messages-to-your-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/adding-user-messages-to-your-cmdlet?branch=pr-en-us-3904) |
[developer/cmdlet/advisory-development-guidelines.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/advisory-development-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/advisory-development-guidelines?branch=pr-en-us-3904) |
[developer/cmdlet/cmdlet-attribute-declaration.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/cmdlet-attribute-declaration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/cmdlet-attribute-declaration?branch=pr-en-us-3904) |
[developer/cmdlet/cmdlet-error-reporting.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/cmdlet-error-reporting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/cmdlet-error-reporting?branch=pr-en-us-3904) |
[developer/cmdlet/cmdlet-overview.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/cmdlet-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/cmdlet-overview?branch=pr-en-us-3904) |
[developer/cmdlet/common-parameter-names.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/common-parameter-names.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/common-parameter-names?branch=pr-en-us-3904) |
[developer/cmdlet/confirmation-messages.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/confirmation-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/confirmation-messages?branch=pr-en-us-3904) |
[developer/cmdlet/creating-a-cmdlet-that-modifies-the-system.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/creating-a-cmdlet-that-modifies-the-system.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/creating-a-cmdlet-that-modifies-the-system?branch=pr-en-us-3904) |
[developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/creating-a-cmdlet-to-access-a-data-store?branch=pr-en-us-3904) |
[developer/cmdlet/creating-a-cmdlet-without-parameters.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/creating-a-cmdlet-without-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/creating-a-cmdlet-without-parameters?branch=pr-en-us-3904) |
[developer/cmdlet/error-reporting-concepts.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/error-reporting-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/error-reporting-concepts?branch=pr-en-us-3904) |
[developer/cmdlet/examples-of-cmdlet-code.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/examples-of-cmdlet-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/examples-of-cmdlet-code?branch=pr-en-us-3904) |
[developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?branch=pr-en-us-3904) |
[developer/cmdlet/how-to-override-input-processing-methods.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/how-to-override-input-processing-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/how-to-override-input-processing-methods?branch=pr-en-us-3904) |
[developer/cmdlet/how-to-request-confirmations.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/how-to-request-confirmations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/how-to-request-confirmations?branch=pr-en-us-3904) |
[developer/cmdlet/how-to-support-jobs.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/how-to-support-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/how-to-support-jobs?branch=pr-en-us-3904) |
[developer/cmdlet/interpreting-errorrecord-objects.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/interpreting-errorrecord-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/interpreting-errorrecord-objects?branch=pr-en-us-3904) |
[developer/cmdlet/invoking-cmdlets-and-scripts-within-a-cmdlet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/invoking-cmdlets-and-scripts-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/invoking-cmdlets-and-scripts-within-a-cmdlet?branch=pr-en-us-3904) |
[developer/cmdlet/non-terminating-errors.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/non-terminating-errors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/non-terminating-errors?branch=pr-en-us-3904) |
[developer/cmdlet/requesting-confirmation-from-cmdlets.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/requesting-confirmation-from-cmdlets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/requesting-confirmation-from-cmdlets?branch=pr-en-us-3904) |
[developer/cmdlet/requesting-confirmation.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/requesting-confirmation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/requesting-confirmation?branch=pr-en-us-3904) |
[developer/cmdlet/stopprocesssample02-sample.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/stopprocesssample02-sample.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/stopprocesssample02-sample?branch=pr-en-us-3904) |
[developer/cmdlet/strongly-encouraged-development-guidelines.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/strongly-encouraged-development-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/strongly-encouraged-development-guidelines?branch=pr-en-us-3904) |
[developer/cmdlet/terminating-errors.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/terminating-errors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/terminating-errors?branch=pr-en-us-3904) |
[developer/cmdlet/users-requesting-confirmation.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/users-requesting-confirmation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/users-requesting-confirmation?branch=pr-en-us-3904) |
[developer/cmdlet/windows-powershell-error-records.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/cmdlet/windows-powershell-error-records.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/windows-powershell-error-records?branch=pr-en-us-3904) |
[developer/prog-guide/creating-a-windows-powershell-container-provider.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/creating-a-windows-powershell-container-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/creating-a-windows-powershell-container-provider?branch=pr-en-us-3904) |
[developer/prog-guide/creating-a-windows-powershell-content-provider.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/creating-a-windows-powershell-content-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/creating-a-windows-powershell-content-provider?branch=pr-en-us-3904) |
[developer/prog-guide/creating-a-windows-powershell-drive-provider.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/creating-a-windows-powershell-drive-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/creating-a-windows-powershell-drive-provider?branch=pr-en-us-3904) |
[developer/prog-guide/creating-a-windows-powershell-item-provider.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/creating-a-windows-powershell-item-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/creating-a-windows-powershell-item-provider?branch=pr-en-us-3904) |
[developer/prog-guide/creating-a-windows-powershell-navigation-provider.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/creating-a-windows-powershell-navigation-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/creating-a-windows-powershell-navigation-provider?branch=pr-en-us-3904) |
[developer/prog-guide/creating-a-windows-powershell-property-provider.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/creating-a-windows-powershell-property-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/creating-a-windows-powershell-property-provider?branch=pr-en-us-3904) |
[developer/prog-guide/getproc04-code-samples.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/getproc04-code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/getproc04-code-samples?branch=pr-en-us-3904) |
[developer/prog-guide/getproc04-csharp-sample-code.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/getproc04-csharp-sample-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/getproc04-csharp-sample-code?branch=pr-en-us-3904) |
[developer/prog-guide/getproc04-vb-net-sample-code.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-Stopprocessing-/developer/prog-guide/getproc04-vb-net-sample-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/getproc04-vb-net-sample-code?branch=pr-en-us-3904) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C13%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903132249341767-3904%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2vA1gPtvJL8SvNSPT%2F4IlLmjaij5P5JoTkPfedaIyBE%3D&st=2019-03-13T22%3A48%3A57Z&se=2019-04-13T22%3A53%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
