### PR TITLE
1-GET-STARTED revision

### PR DESCRIPTION
**Pull request by ugotjelly**
Made writing more concise by shortening sentences, and removing contractions.

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[32a4374](https://github.com/ugotjelly/PowerShell-Docs/pull/3826/commits/32a43741b6f231338ae81da2386c07e52704a52b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[32a4374](https://github.com/ugotjelly/PowerShell-Docs/pull/3826/commits/32a43741b6f231338ae81da2386c07e52704a52b)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 50 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[32a4374](https://github.com/ugotjelly/PowerShell-Docs/pull/3826/commits/32a43741b6f231338ae81da2386c07e52704a52b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[contributing/1-GET-STARTED.md](https://github.com/ugotjelly/PowerShell-Docs/blob/staging/contributing/1-GET-STARTED.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C10%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903100850234199-3826%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hYhKJLLQqQXbQ18r2UO6280BQ6VXjz%2Bc8OY3hbzhTKI%3D&st=2019-03-10T08%3A59%3A56Z&se=2019-04-10T09%3A04%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@ugotjelly Thanks for the edits. The contractions are allowed and encouraged by the Microsoft Style Guide. But I have no problem with the change.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fa65a7f](https://github.com/ugotjelly/PowerShell-Docs/pull/3826/commits/fa65a7f92cd302e43cf6b8c3806ba8b44c9a2f3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[contributing/1-GET-STARTED.md](https://github.com/ugotjelly/PowerShell-Docs/blob/staging/contributing/1-GET-STARTED.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C11%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903111752337949-3826%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nYqX6vYchJMo0r9bfh0DYs5Fc%2Fz%2FOYVoQ4hYFUynBpo%3D&st=2019-03-11T18%3A01%3A31Z&se=2019-04-11T18%3A06%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
