### PR TITLE
Copyedits and added notes about PSReadLine to Clear-History

### LINKED ISSUE #3551: Note about PSReadLine
It is known that `Clear-History` doesn't actually "clear the history", so it may be worth adding a note about `PSReadLine`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0072f971-6e75-8f0c-6fbb-de3ad10d7ee3
* Version Independent ID: 0f2c7a2d-992e-0005-6c10-70067b36527b
* Content: [Clear-History (Microsoft.PowerShell.Core)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/clear-history?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Clear-History.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

### PR DESCRIPTION
**Pull request by davidsmatlak**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Closes #3551
Copyedited document
Added notes about PSReadLine

Acrolinx scores
Original version: 88
Updated version: 85 (94 with Acrolinx suggestion)
Acrolinx suggests ID rather than Id.
Id is a valid Clear-History parameter and Get-History property used in the document.

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[afa4f0b](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/afa4f0b0d864791bc2da6e57f019f8752c4373e3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[afa4f0b](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/afa4f0b0d864791bc2da6e57f019f8752c4373e3)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[afa4f0b](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/afa4f0b0d864791bc2da6e57f019f8752c4373e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/3.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-3.0&branch=pr-en-us-3756) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/4.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-4.0&branch=pr-en-us-3756) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/5.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-5.0&branch=pr-en-us-3756) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/5.1/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-5.1&branch=pr-en-us-3756) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/6/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-6&branch=pr-en-us-3756) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C22%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902222012552367-3756%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PI%2FJCkr4ltWRFvlwSS6%2Bqhp1XP8BJD2L7cbZezyRFkA%3D&st=2019-02-22T20%3A25%3A42Z&se=2019-03-25T20%3A30%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[8c2de12](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/8c2de12ea46fc96851497b4e49ba6fc8a063a9cf)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[8c2de12](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/8c2de12ea46fc96851497b4e49ba6fc8a063a9cf)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 49 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[8c2de12](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/8c2de12ea46fc96851497b4e49ba6fc8a063a9cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/3.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-3.0&branch=pr-en-us-3756) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/4.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-4.0&branch=pr-en-us-3756) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/5.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-5.0&branch=pr-en-us-3756) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/5.1/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-5.1&branch=pr-en-us-3756) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/6/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-6&branch=pr-en-us-3756) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C23%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902230058393274-3756%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TkvF2Fw3%2F%2BXAwHwKVWNe%2FL2BMq1NC6DUqeB4BULTp4Q%3D&st=2019-02-23T01%3A06%3A52Z&se=2019-03-26T01%3A11%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidsmatlak** [comment]
Rewrote the description section and fixed the links. Kept the do not merge tag until we review this PR next week.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[49e1850](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/49e1850e8b042c3a5b43db53fdec5ac15116be06)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[49e1850](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/49e1850e8b042c3a5b43db53fdec5ac15116be06)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 48 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[49e1850](https://github.com/davidsmatlak/PowerShell-Docs/pull/3756/commits/49e1850e8b042c3a5b43db53fdec5ac15116be06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/3.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-3.0&branch=pr-en-us-3756) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/4.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-4.0&branch=pr-en-us-3756) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/5.0/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-5.0&branch=pr-en-us-3756) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/5.1/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-5.1&branch=pr-en-us-3756) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Core/Clear-History.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3551/reference/6/Microsoft.PowerShell.Core/Clear-History.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-history?view=powershell-6&branch=pr-en-us-3756) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C25%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201902251937586146-3756%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kme1PFLsnIFhofjoErshLzEDmF1a%2BdXAhKQjjGjDqCY%3D&st=2019-02-25T19%3A46%3A24Z&se=2019-03-28T19%3A51%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
