### PR TITLE
Added docs for ReplyTo parameter in Send-MailMessage

### LINKED ISSUE #3602: Add documentation for new -ReplyTo parameter in Send-MailMessage
Issue Details
-----------------
Pending the acceptance of powershell/powershell#8727, the new `-ReplyTo` parameter in the `Send-MailMessage` cmdlet will need documentation added.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

### PR DESCRIPTION
**Pull request by anmenaga**
Fix #3602 

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [X] The documented feature was introduced in version 6.2 of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[1c7db65](https://github.com/anmenaga/PowerShell-Docs/pull/4035/commits/1c7db6556793fe52c828d65df3113a89f9852774)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903221943477958-4035%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3y%2FtRGuVnRzYXIJ%2F7GnrR7GQ0m%2FgvXEXS1AaAgPgeho%3D&st=2019-03-22T19%3A42%3A55Z&se=2019-04-22T19%3A47%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[7acf7e0](https://github.com/anmenaga/PowerShell-Docs/pull/4035/commits/7acf7e0942b97b69acad31ae5c8f90c55a6e79bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.editorconfig](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/.editorconfig) | :white_check_mark:Succeeded | |
[contributing/6-UPDATING-REFERENCE.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/contributing/6-UPDATING-REFERENCE.md) | :white_check_mark:Succeeded | |
[developer/prog-guide/how-to-create-a-windows-powershell-provider.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/developer/prog-guide/how-to-create-a-windows-powershell-provider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/prog-guide/how-to-create-a-windows-powershell-provider?branch=pr-en-us-4035) |
[reference/3.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/3.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-3.0&branch=pr-en-us-4035) (powershell-3.0) |
[reference/3.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/3.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-3.0&branch=pr-en-us-4035) (powershell-3.0) |
[reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/set-variable?view=powershell-3.0&branch=pr-en-us-4035) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/4.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-4.0&branch=pr-en-us-4035) (powershell-4.0) |
[reference/4.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/4.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-4.0&branch=pr-en-us-4035) (powershell-4.0) |
[reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/set-variable?view=powershell-4.0&branch=pr-en-us-4035) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/5.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-5.0&branch=pr-en-us-4035) (powershell-5.0) |
[reference/5.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/5.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-5.0&branch=pr-en-us-4035) (powershell-5.0) |
[reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/set-variable?view=powershell-5.0&branch=pr-en-us-4035) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-5.1&branch=pr-en-us-4035) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-5.1&branch=pr-en-us-4035) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/set-variable?view=powershell-5.1&branch=pr-en-us-4035) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |
[reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/set-variable?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |
[reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/samples/creating-get-winevent-queries-with-filterhashtable?view=powershell-3.0&branch=pr-en-us-4035) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/samples/creating-get-winevent-queries-with-filterhashtable?view=powershell-4.0&branch=pr-en-us-4035) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/samples/creating-get-winevent-queries-with-filterhashtable?view=powershell-5.0&branch=pr-en-us-4035) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/samples/creating-get-winevent-queries-with-filterhashtable?view=powershell-5.1&branch=pr-en-us-4035) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/samples/creating-get-winevent-queries-with-filterhashtable?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |
[reference/docs-conceptual/samples/media/creating-get-winEvent-queries-with-filterhashtable/keywords.png](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/docs-conceptual/samples/media/creating-get-winEvent-queries-with-filterhashtable/keywords.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/docs-conceptual/samples/media/creating-get-winevent-queries-with-filterhashtable/keywords.png?branch=pr-en-us-4035) |
[reference/docs-conceptual/samples/media/creating-get-winEvent-queries-with-filterhashtable/providername.png](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/docs-conceptual/samples/media/creating-get-winEvent-queries-with-filterhashtable/providername.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/docs-conceptual/samples/media/creating-get-winevent-queries-with-filterhashtable/providername.png?branch=pr-en-us-4035) |
[reference/docs-conceptual/toc.yml](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/overview?view=powershell-3.0&branch=pr-en-us-4035) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/overview?view=powershell-4.0&branch=pr-en-us-4035) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/overview?view=powershell-5.0&branch=pr-en-us-4035) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/overview?view=powershell-5.1&branch=pr-en-us-4035) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/overview?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903281640385364-4035%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QDaCMnvyNkZYylszeKZ9Nj4yQmmuwo%2BxomHX9DW5Ztc%3D&st=2019-03-28T16%3A41%3A07Z&se=2019-04-28T16%3A46%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[f5dc0ff](https://github.com/anmenaga/PowerShell-Docs/pull/4035/commits/f5dc0ff9becfb304938ee9fb66daf331c988e499)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903281653027466-4035%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oITF1nTMTmWgxVEiPMYYnFo43oXa22TXWvBkT%2BHg1UQ%3D&st=2019-03-28T16%3A52%3A26Z&se=2019-04-28T16%3A57%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anmenaga** [comment]
@sdwheeler Updated; please take a look again.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[f5dc0ff](https://github.com/anmenaga/PowerShell-Docs/pull/4035/commits/f5dc0ff9becfb304938ee9fb66daf331c988e499)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/anmenaga/PowerShell-Docs/blob/ReplyToInSendMailMessage/reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6&branch=pr-en-us-4035) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903281653141502-4035%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MoFGoEjURNshBhTpsgSiY5WCnQ1kQMBEyqKFLO9ZmUg%3D&st=2019-03-28T16%3A56%3A53Z&se=2019-04-28T17%3A01%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
