### PR TITLE
[DO NOT MERGE] - Test PR for Comparison

### PR DESCRIPTION
**Pull request by chasewilson**
# PR Summary

A test PR to see which navigation experience is better.

## PR Context

This is a test PR to see the navigational experience as compared to PR #7812
Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Sample scripts
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Language Spec
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [x] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [x] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by chasewilson** [comment]
Hey @SetTrend, we are taking a look to see if the navigational experience would be better and the reader would be able to navigate the page from the right side nav section. 

We'd love your feedback here. This isn't to replace your pr, only to see the experience and we'd like to have the final decision in your PR. 

@sdwheeler, this is the temp pr we talked about. Feel free to leave your feedback here when you have a chance to review.

**Comment by sdwheeler** [comment]
After reviewing the rendered version in this PR, I don't like the results. Closing this PR.

**Comment by SetTrend** [comment]
I'm somehow lost here. This PR doesn't resemble mine, yet I'm listed as the one who created it.

@chasewilson:

Reading the docs with my browser window set like depicted in the following image I don't see a side navigation:

Rendering 940 pixels width

I'm using this browser window setting so I can continue programming while reading, or copy/pasting, the docs.

**Comment by SetTrend** [comment]
Ah, now I'm getting it. You've been trying to test a different design approach to get a similar result.

Does my previous comment above shed some light on the issue I tried to solve with my PR?

Thank you for taking the time! 👍

**Pull request closed without merging**
