### PR TITLE
Installer-files for Raspberry Pi OS x64

### PR DESCRIPTION
**Pull request by skille**
Clearify how to intall on Raspberry Pi OS running x64

# PR Summary

## PR Context

Check the boxes below to indicate the content affected by this PR.

**Repository or docset configuration**
- [ ] Repo documentation and configuration (.git/.github/.vscode etc.)
- [ ] Docs build files (.openpublishing.* and build scripts)
- [ ] Docset configuration (docfx.json, mapping, bread, module folder)

**Conceptual documentation**
- [x] Files in docs-conceptual

**Cmdlet reference & about_ topics**
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all
relevant versions. Check the boxes below to indicate the versions affected by this change.

- [ ] Preview content
- [ ] Version 7.2 content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [x] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**. If the PR is work in progress,
  please add the prefix `WIP:` or `[WIP]` to the beginning of the title and remove the prefix when
  the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by skille** [comment]
Added how to install on Raspberry Pi OS running arm64.

**Comment by sdwheeler** [comment]
@skille which Raspberry Pi devices support Arm64?

**Comment by skille** [comment]
The Raspberry Pi 3 and 4 are 64-bit compatible.
Only the Pi 4 has a model equipped with more than 4GB of memory, making
reasonable use of a 64 bit environment.
The operating system is still in beta, but nonetheless is the choice for
making use of memory consuming applications.

The installer images are available for download here:
https://downloads.raspberrypi.org/raspios_arm64/images/

Best regards, Trond Skile

**Comment by sdwheeler** [comment]
OK. Since 64-bit is not officially support by Raspberry Pi yet we can't support it. We will update the documentation once it is supported by Raspberry Pi and has been tested by the PowerShell team.

**Comment by skille** [comment]
I think this is wrong.
The hardware supports 64bit instructions, and there also are other linux
distros that are out of beta.
It is just the operating system itself from Raspberry Pi Foundation that is
in beta.

Anyway, this is about the packages built for 64bit versions, they are from
Microsoft and are released as stable, and should thus be documented for
usage for those who need to use those packages instead.

**Comment by sdwheeler** [comment]
This article is about Raspberry Pi OS and what we support. 

Also, I am not saying that it doesn't work. I am saying that we haven't tested it and we don't support it. See https://docs.microsoft.com/powershell/scripting/install/powershell-support-lifecycle#supported-platforms

**Pull request closed without merging**
