### PR TITLE
Add SkipEditionCheck switch docs, update CompatiblePSEditions docs

### PR DESCRIPTION
**Pull request by rjmholt**
Resolves https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3433.

Adds documentation for the `-SkipEditionCheck` parameter on `Import-Module` and `Get-Module` and updates information about the `CompatiblePSEditions` field in documentation.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version (6.1) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3bd5311](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/3bd5311e3f77d11c420c4521c386b927c7619c8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/concepts/module-psedition-support?branch=pr-en-us-4039) |
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/get-module?view=powershell-6&branch=pr-en-us-4039) (powershell-6) |
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/import-module?view=powershell-6&branch=pr-en-us-4039) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903222107380459-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MdQAuDPjZlnY7gJ6%2F98Q2c%2BDFwNOIcNxxEOtmpIKNtM%3D&st=2019-03-22T21%3A06%3A56Z&se=2019-04-22T21%3A11%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[2c22ec6](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/2c22ec6c6e29c085cc4e4cd5d381fec5369648d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_powershell_editions?view=powershell-6&branch=pr-en-us-4039) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)
[gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/concepts/module-psedition-support?branch=pr-en-us-4039) |
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/get-module?view=powershell-6&branch=pr-en-us-4039) (powershell-6) |
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/import-module?view=powershell-6&branch=pr-en-us-4039) (powershell-6) |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **Line 229**: **[Warning]** Invalid file link:(~/../gallery/concepts/module-psedition-support.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903281951571435-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uYY02ws7uKft24ShOlW5MX2jArLegx5FV1q%2B5fZHers%3D&st=2019-03-28T19%3A51%3A44Z&se=2019-04-28T19%3A56%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[4e4ed3d](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/4e4ed3d0f8d1e24251b9a177f8635f1ccb6c969a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md)
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md)
[gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md) | :warning:Warning | | [Details](#user-content-gallery%2Fconcepts%2Fmodule-psedition-support.md)
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Get-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :634:(6816) &#39;

[about_PowerShell_Editions][]

[about_PowerS...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions][]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Import-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :1054:(11573) &#39;

[about_PowerShell_Editions]

[about_PowerShe...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="gallery%2Fconcepts%2Fmodule-psedition-support.md"></a>
### [gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/../reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md).
 - **Line 261**: **[Warning]** Invalid file link:(~/../reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md).

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **Line 240**: **[Warning]** Invalid file link:(~/../gallery/concepts/module-psedition-support.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903281959222452-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OBxEZZDWNa3BuQAdQlLSxzaTRFS37WUXxd0iIQenXOk%3D&st=2019-03-28T19%3A58%3A28Z&se=2019-04-28T20%3A03%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rjmholt** [comment]
@sdwheeler don't merge yet, I have another commit that I need to rectify with your last one

**Comment by rjmholt** [comment]
Ok done

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[2d67453](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/2d674535e322fd37346b2a7ae10a1e1eff0ef806)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md)
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md)
[gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md) | :warning:Warning | | [Details](#user-content-gallery%2Fconcepts%2Fmodule-psedition-support.md)
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Get-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :634:(6816) &#39;

[about_PowerShell_Editions][]

[about_PowerS...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions][]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Import-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :1054:(11573) &#39;

[about_PowerShell_Editions]

[about_PowerShe...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="gallery%2Fconcepts%2Fmodule-psedition-support.md"></a>
### [gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/../reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md).
 - **Line 261**: **[Warning]** Invalid file link:(~/../reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md).

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903282005076266-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0xiBb5STl%2F91dPytceLI8NvUUwOy1zyhK74mNhT825o%3D&st=2019-03-28T20%3A04%3A48Z&se=2019-04-28T20%3A09%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d3db7df](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/d3db7dfd4ec54bf3d4d5ea4a32691223d63d254d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md)
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md)
[gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md) | :warning:Warning | | [Details](#user-content-gallery%2Fconcepts%2Fmodule-psedition-support.md)
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Get-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :634:(6816) &#39;

[about_PowerShell_Editions][]

[about_PowerS...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions][]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Import-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :1059:(11573) &#39;

[about_PowerShell_Editions]

[about_PowerShe...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="gallery%2Fconcepts%2Fmodule-psedition-support.md"></a>
### [gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/../reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md).
 - **Line 261**: **[Warning]** Invalid file link:(~/../reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md).

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903282008574197-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oZnm2iBLkhrXKPMzkQ8PTeUWXpq7dFGA0oF4%2Fj%2BJVZU%3D&st=2019-03-28T20%3A09%3A15Z&se=2019-04-28T20%3A14%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[60e20b0](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/60e20b07afb6821c117408e1a48e26a07ecb3d1c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md)
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md)
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Get-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :634:(6816) &#39;

[about_PowerShell_Editions][]

[about_PowerS...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions][]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Import-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :1059:(11573) &#39;

[about_PowerShell_Editions]

[about_PowerShe...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903282012286329-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tsCL%2BDTaXEmPYqHFJ%2BWV4QJsjRLGtfgWVyp8AWSgKF0%3D&st=2019-03-28T20%3A13%3A31Z&se=2019-04-28T20%3A18%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3c0e6d2](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/3c0e6d286f573035fde44320164cdd560a50ce8d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md)
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FImport-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Core/Import-Module.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :1059:(11573) &#39;

[about_PowerShell_Editions]

[about_PowerShe...&#39;
 Expect hyperlink, but got [about_PowerShell_Editions]
[about_PowerShell_Editions]: About/about_PowerShell_Editions.md

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903282017300339-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UeELyKsqYGXULx7lzTJaywQuY6FbxC4k%2BfmS7dZ1A9s%3D&st=2019-03-28T20%3A17%3A55Z&se=2019-04-28T20%3A22%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c28a2dc](https://github.com/rjmholt/PowerShell-Docs/pull/4039/commits/c28a2dc5cd6acada4a6304a14a9324ecda949b3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_powershell_editions?view=powershell-6&branch=pr-en-us-4039) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md)
[gallery/concepts/module-psedition-support.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/gallery/concepts/module-psedition-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/concepts/module-psedition-support?branch=pr-en-us-4039) |
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/get-module?view=powershell-6&branch=pr-en-us-4039) (powershell-6) |
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/import-module?view=powershell-6&branch=pr-en-us-4039) (powershell-6) |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_PowerShell_Editions.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md](https://github.com/rjmholt/PowerShell-Docs/blob/skipedition-psedition-updates/reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903282018532249-4039%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nfwB2Z1rApclFyE0OEX4ab5ZIv990My0GNJdN0eAvWE%3D&st=2019-03-28T20%3A22%3A51Z&se=2019-04-28T20%3A27%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
