### PR TITLE
C90810: Adding two spaces at the end of lines

### PR DESCRIPTION
**Pull request by v-makoud**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.

### CODE REVIEW

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[45c0c55](https://github.com/v-makoud/PowerShell-Docs/pull/4333/commits/45c0c553317af90e5b0f1afb77e1bc52f5492a09)_: 

:clock10: **Full build**: the average full build time is _13 min(s) 25 sec(s)_, this is based on the last _36_ build(s) for this repository.

**Comment by v-makoud** [comment]
#sign-off

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[45c0c55](https://github.com/v-makoud/PowerShell-Docs/pull/4333/commits/45c0c553317af90e5b0f1afb77e1bc52f5492a09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md](https://github.com/v-makoud/PowerShell-Docs/blob/patch-7/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-3.0&branch=pr-en-us-4333) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-4.0&branch=pr-en-us-4333) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-5.0&branch=pr-en-us-4333) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-5.1&branch=pr-en-us-4333) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/install/installing-powershell-core-on-windows?view=powershell-6&branch=pr-en-us-4333) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C22%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201905220623187815-4333%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2zmYd1L%2FDBUU0OwXA3H%2FwxFNI0GIX3VQB8BditsQKSw%3D&st=2019-05-22T06%3A33%3A14Z&se=2019-06-22T06%3A38%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@v-makoud Why are you adding spaces there? They are not needed. Those are definitions for reference links used in the document. Those lines are not rendered at the bottom of the page.

**Comment by sdwheeler** [comment]
@v-makoud I am closing this for lack of response. This change does nothing to the rendering.

**Comment by v-makoud** [comment]
@sdwheeler The problem occurs during transformation from .md to .xlf. It breaks formating on loc pages.

**Comment by sdwheeler** [comment]
@v-makoud I don't know what .xlf is. But it sounds like a but in the transformation. It is valid markdown that must be supported.

**Pull request closed without merging**
