### PR TITLE
M32234: Missing word

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @Saisang, @SydneyhSmith, @sdwheeler, 
Translator has reported possible source content issue. 
Description: Is there something missing between "an" and "publishing"? Otherwise, this sentence is ungrammatical. Please advise.
Please review the comment tag added and reply with explanation if fix is needed or not. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/concepts/publishing-guidelines.md](https://github.com/v-makoud/PowerShell-Docs/blob/patch-3/gallery/concepts/publishing-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/concepts/publishing-guidelines?branch=pr-en-us-3203) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C30%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201810300825263965-3203%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yoTf1QON88fV4cJ9emj730yq9nRy5ADhfVjmP3X4PDY%3D&st=2018-10-30T08%3A34%3A33Z&se=2018-11-30T08%3A39%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@v-makoud "an" should have been "and".

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/concepts/publishing-guidelines.md](https://github.com/v-makoud/PowerShell-Docs/blob/patch-3/gallery/concepts/publishing-guidelines.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/concepts/publishing-guidelines?branch=pr-en-us-3203) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C30%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201810301354523158-3203%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6HIaf7KFvJEiDamGhbrwQdVQj86qDIRb4iMPv5dbWDs%3D&st=2018-10-30T14%3A04%3A23Z&se=2018-11-30T14%3A09%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@v-makoud I just realized that this PR was to the live branch. Do not target the live branch. The staging branch is the default branch and should be the target of all changes.

**Comment by v-makoud** [comment]
Thank you @sdwheeler for your response, but the source is still incorrect. Can you please review the sentence. I created new PR in the staging branch here: https://github.com/PowerShell/PowerShell-Docs/pull/3251
Best regards

**Pull request merged**
