### PR TITLE
Documentation changes for new -SecurityDescriptorSddl parameter in Set-Service

### PR DESCRIPTION
**Pull request by kvprasoon**
Version(s) of document impacted
------------------------------
- [x] Impacts 7 document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version (6.nextversion) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[cba57f2](https://github.com/kvprasoon/PowerShell-Docs/pull/3880/commits/cba57f22e12bc36d6714385c7e93065d8f7d50ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Management/Set-Service.md](https://github.com/kvprasoon/PowerShell-Docs/blob/srv-sdset-doc/reference/6/Microsoft.PowerShell.Management/Set-Service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/set-service?view=powershell-6&branch=pr-en-us-3880) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C12%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903121955322456-3880%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t2SWuJHeLewR1kLkQE%2BMGOKH59HFNJ0UnHM7h4ZGYqE%3D&st=2019-03-12T19%3A55%3A14Z&se=2019-04-12T20%3A00%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@kvprasoon Your code change has been merged. But this PR is changing the v6 document. Can you move the changes from v6 to v7?

Thanks.

**Comment by kvprasoon** [comment]
Thanks, I've reverted the changes from v6 and add them to v7. Just noticed that
`online version: https://go.microsoft.com/fwlink/?linkid=2096214` is wrong.

**Comment by sdwheeler** [comment]
@kvprasoon Thanks. I will open an new issue for the broken FWLink.

**Pull request merged**
