### PR TITLE
Updated Encoding parameter for Add-Content

### PR DESCRIPTION
**Pull request by davidsmatlak**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Related to Issue #2000
Updated Encoding parameter and YAML for Add-Content
Style updates
Paragraph reflows
Fixed links

Acrolinx scores
Original version: 89
Updated version: 95

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[2c9bcf3](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/2c9bcf3b540414c6299748b977aab40da6a7cca1)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[2c9bcf3](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/2c9bcf3b540414c6299748b977aab40da6a7cca1)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[2c9bcf3](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/2c9bcf3b540414c6299748b977aab40da6a7cca1)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 54 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[2c9bcf3](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/2c9bcf3b540414c6299748b977aab40da6a7cca1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/3.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-3.0&branch=pr-en-us-3617) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/4.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-4.0&branch=pr-en-us-3617) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/5.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-5.0&branch=pr-en-us-3617) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/5.1/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-5.1&branch=pr-en-us-3617) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/6/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-6&branch=pr-en-us-3617) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901290134080449-3617%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oDCaepJMydOnbJPMD%2F6JwIQDq4Kt3VVobELTiwMCL%2FQ%3D&st=2019-01-29T01%3A43%3A12Z&se=2019-03-01T01%3A48%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidsmatlak** [comment]
Please do not merge. I need to fix some syntax formats.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4df9aa](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/d4df9aa204f9390c24cf59189aa6ef1106660b90)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4df9aa](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/d4df9aa204f9390c24cf59189aa6ef1106660b90)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4df9aa](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/d4df9aa204f9390c24cf59189aa6ef1106660b90)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 54 sec(s)_

**Comment by davidsmatlak** [comment]
Updated the PR with changes to syntax formats.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4df9aa](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/d4df9aa204f9390c24cf59189aa6ef1106660b90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/3.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-3.0&branch=pr-en-us-3617) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/4.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-4.0&branch=pr-en-us-3617) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/5.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-5.0&branch=pr-en-us-3617) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/5.1/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-5.1&branch=pr-en-us-3617) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/6/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-6&branch=pr-en-us-3617) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901291850455831-3617%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0JqX3zQtPv61jv5Qsq7RvUtmGfWCT6TogofoPBwFZLA%3D&st=2019-01-29T18%3A59%3A29Z&se=2019-03-01T19%3A04%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fb0cbbe](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/fb0cbbe6407fbf7ef8441f5a5ea4dcd9a267864b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fb0cbbe](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/fb0cbbe6407fbf7ef8441f5a5ea4dcd9a267864b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fb0cbbe](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/fb0cbbe6407fbf7ef8441f5a5ea4dcd9a267864b)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 53 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fb0cbbe](https://github.com/davidsmatlak/PowerShell-Docs/pull/3617/commits/fb0cbbe6407fbf7ef8441f5a5ea4dcd9a267864b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/3.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-3.0&branch=pr-en-us-3617) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/4.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-4.0&branch=pr-en-us-3617) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/5.0/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-5.0&branch=pr-en-us-3617) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/5.1/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-5.1&branch=pr-en-us-3617) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Management/Add-Content.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue2000-addcontent/reference/6/Microsoft.PowerShell.Management/Add-Content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/add-content?view=powershell-6&branch=pr-en-us-3617) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201901292056309411-3617%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=u%2B%2FZpjmQlYvbalhOJ5%2BVkqrQ8bvnhGs01hddY1toF8I%3D&st=2019-01-29T21%3A10%3A05Z&se=2019-03-01T21%3A15%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
