### PR TITLE
Migration from MSDN missed a spot

### PR DESCRIPTION
**Pull request by SamB**
Specifically, there's a link to "Installing the Windows PowerShell SDK" that still points to MSDN instead of the local article.  Lets fix that.

### CODE REVIEW

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[b9f396b](https://github.com/SamB/PowerShell-Docs/pull/4318/commits/b9f396b37f472d286acb7be9b02f375196f40b8d)_: 

:clock10: **Full build**: the average full build time is _13 min(s) 53 sec(s)_, this is based on the last _13_ build(s) for this repository.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[b9f396b](https://github.com/SamB/PowerShell-Docs/pull/4318/commits/b9f396b37f472d286acb7be9b02f375196f40b8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/installing-the-windows-powershell-sdk.md](https://github.com/SamB/PowerShell-Docs/blob/migration-missed-a-spot/developer/installing-the-windows-powershell-sdk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/installing-the-windows-powershell-sdk?branch=pr-en-us-4318) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C19%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201905190354270826-4318%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=am58ns%2FwgdAVeWCmPvhRZ3EaFuJ4GDcZ5yCe6HzrdaM%3D&st=2019-05-19T04%3A04%3A38Z&se=2019-06-19T04%3A09%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SamB** [comment]
Rats, I was so hoping that would fail :-(.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[b35a251](https://github.com/SamB/PowerShell-Docs/pull/4318/commits/b35a2516bf434f32926f790848fca4c7f5a1a83d)_: 

:clock10: **Full build**: the average full build time is _13 min(s) 54 sec(s)_, this is based on the last _14_ build(s) for this repository.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[b35a251](https://github.com/SamB/PowerShell-Docs/pull/4318/commits/b35a2516bf434f32926f790848fca4c7f5a1a83d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/installing-the-windows-powershell-sdk.md](https://github.com/SamB/PowerShell-Docs/blob/migration-missed-a-spot/developer/installing-the-windows-powershell-sdk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/installing-the-windows-powershell-sdk?branch=pr-en-us-4318) |
[developer/windows-powershell.md](https://github.com/SamB/PowerShell-Docs/blob/migration-missed-a-spot/developer/windows-powershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/windows-powershell?branch=pr-en-us-4318) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C19%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201905190422078896-4318%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ad7q7yMa2k5oLHVJC19pMQbzlLIQ4Y5GMv8gGMNeDr8%3D&st=2019-05-19T04%3A32%3A21Z&se=2019-06-19T04%3A37%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@SamB The assetids are deprecated now. We are in the process of removing them.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[66c36cc](https://github.com/SamB/PowerShell-Docs/pull/4318/commits/66c36cc3e149addac61c2a1e32c7a94e544af49b)_: 

:clock10: **Full build**: the average full build time is _13 min(s) 54 sec(s)_, this is based on the last _18_ build(s) for this repository.

**Comment by zjalexander** [comment]
Docs Build status updates of commit _[66c36cc](https://github.com/SamB/PowerShell-Docs/pull/4318/commits/66c36cc3e149addac61c2a1e32c7a94e544af49b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/windows-powershell.md](https://github.com/SamB/PowerShell-Docs/blob/migration-missed-a-spot/developer/windows-powershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/windows-powershell?branch=pr-en-us-4318) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C20%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201905201718265631-4318%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MWn9Om1iSjwSW3IXyLXOeAeXOMpWH2y7SvVSeszadfI%3D&st=2019-05-20T17%3A26%3A27Z&se=2019-06-20T17%3A31%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
