### PR TITLE
line 101: typo in path name (disk name)

### PR DESCRIPTION
**Pull request by AndreyMatrosov**
} 3>&1 2>&1 > P:\Temp\redirection.log
correct is
} 3>&1 2>&1 > C:\Temp\redirection.log

# PR Summary

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

## PR Checklist

- [ ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ ] PR has a meaningful title
- [ ] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Review by chasewilson — CHANGES_REQUESTED** [review]
This is a great catch @AndreyMatrosov! Thanks for the contribution. Would you be able to make the changes to all versions before we merge this in?

**Comment by chasewilson** [comment]
@AndreyMatrosov , do you plan on finishing this PR? If you no longer have the time I can create a new PR myself and credit you for  the work there?

**Comment by AndreyMatrosov** [comment]
I apologize for not answering right away. I,ll close it in a couple hours.

**Comment by chasewilson** [comment]
> I apologize for not answering right away. I,ll close it in a couple hours.

No worries @AndreyMatrosov just wanted to make sure you get your changes in :)

**Comment by AndreyMatrosov** [comment]
I created pull requests to all versions of PowerShell where the typo is.
I am a novice in IT (now I am passing DevOps course in EPAM), and I don't properly sure that I clearly did what you wrote. I don't want to waste your time, so if I wrong, please, correct it yourself or give me more detailed instructions on what to do and I'll be grateful if you write to me if I was wrong about what I had to do to correctly execute what you wrote.
I apologize for the mistakes, cause English isn't my native language.

**Comment by chasewilson** [comment]
Hi @AndreyMatrosov, I will do my best to speak clearly and you can ask me anything if it doesn't make sense.

Your changes were good and don't need to change. However, you created 4 pull requests, 1 for each version, you can use [git](https://git-scm.com/) to connect to GitHub and edit multiple files for a single Pull Request using something like [VsCode](https://code.visualstudio.com/) to edit them. 

You can read the documentation about using [VSCode and github](https://code.visualstudio.com/docs/editor/github) as well as their other documentation. 

Good luck in your career! thank you for the contribution and feel free to reach out!

**Pull request merged**
