### PR TITLE
Update everything-about-hashtable.md add one more thing

### PR DESCRIPTION
**Pull request by Kagre**
One more fun thing you can do with hashtables?

# PR Summary

## PR Checklist

- [ ] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [ ] **Summary:** This PR's summary describes the scope and intent of the change.
- [ ] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [ ] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
Hi @Kagre, thanks for this contribution! Unfortunately, I'm not sure I see what this adds to the article.

It reads to me like the point you're making here is that in PowerShell, you can assign a hashtable or ordered dictionary to an instance of a class that has a hashtable/ordered dictionary property.

I'm not sure that needs calling out specifically, since that's how properties for types in PowerShell work generally. Is there something I'm missing here?

I do think this could make for a good community blog post if you have specific examples of when you would use this technique over just using hashtables or ordered dictionaries.

**Comment by sdwheeler** [comment]
Closing this PR but willing to discuss possible a Community Blog post.

**Comment by Kagre** [comment]
Hi @michaeltlombardi, thank you for taking the time to look at my PR; I'm not very familiar with the github process, so please let me know if this is not the place for a discussion. Also, for context my version of PowerShell is Windows PowerShell v5.1 on Windows 10.

Inline compiled code in PowerShell(PS) is probably about as common place as inline assembly is, and I agree that assigning/passing a hashtable(HT) or ordered dictionary(OD) to a prebaked 3rd party class already looking for one isn't much of a novelty nor an operation exclusive to HTs/ODs. The interesting part(at least to me) comes when I rewrite parts of my PS code as compiled code; in which case I can share a HT back and forth between both coding contexts without incurring a big conversion hit as long as I pay attention to some additional coding details on the compiled side which don't show up on the PowerShell side.

(As a side note, this sharing process reminds me a little bit of the `using` statement, except without the serialization).

**Comment by sdwheeler** [comment]
A blog post about inline compiled code would be a good topic for the Community blog. Open an issue at https://github.com/PowerShell/Community-Blog/issues so we can discuss it there.

**Pull request closed without merging**
