### PR TITLE
typo: ISEincludes -> ISE includes

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[8dad87b](https://github.com/nschonni/PowerShell-Docs/pull/3976/commits/8dad87bff0a4be9506c72cb62618bc3f1a2f4669)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[8dad87b](https://github.com/nschonni/PowerShell-Docs/pull/3976/commits/8dad87bff0a4be9506c72cb62618bc3f1a2f4669)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/ISE/New-IseSnippet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-ISEincludes/reference/5.0/ISE/New-IseSnippet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/ise/new-isesnippet?view=powershell-5.0&branch=pr-en-us-3976) (powershell-5.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C14%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903141605452542-3976%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2UT7N3Km9XJO1OQ4L6B%2BbO4gX1THQJi79%2FD67UCMzZg%3D&st=2019-03-14T16%3A05%3A30Z&se=2019-04-14T16%3A10%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nschonni** [comment]
Re-opening to try and unstick CLA

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[8dad87b](https://github.com/nschonni/PowerShell-Docs/pull/3976/commits/8dad87bff0a4be9506c72cb62618bc3f1a2f4669)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/ISE/New-IseSnippet.md](https://github.com/nschonni/PowerShell-Docs/blob/typo-ISEincludes/reference/5.0/ISE/New-IseSnippet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/ise/new-isesnippet?view=powershell-5.0&branch=pr-en-us-3976) (powershell-5.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C14%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903141736095854-3976%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rwoohSEb1ToXGku9NE4moH%2FaZ5JYrjkF9TFd9W1aSIM%3D&st=2019-03-14T17%3A35%3A56Z&se=2019-04-14T17%3A40%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
