### PR TITLE
Fix Certificate Provider example for .NotAfter

### PR DESCRIPTION
**Pull request by yecril71pl**
# PR Summary

The example did not work as intended.

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [X] Version 7.1 preview content
- [X] Version 7.0 content
- [X] Version 6 content
- [X] Version 5.1 content

## PR Checklist

- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [X] PR is targeted at the _staging_ branch
- [X] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [X] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by yecril71pl** [comment]
I have rewritten the example so as to avoid performing the same operation for each item in a loop.  Please confirm that you prefer keeping this misleading example.

**Comment by yecril71pl** [comment]
You may have missed my answer-question above.

**Comment by chasewilson** [comment]
> I have rewritten the example so as to avoid performing the same operation for each item in a loop. Please confirm that you prefer keeping this misleading example.

I can see the merit in not repeating the process more than necessary. Go ahead and keep your example, copy it to the other versions of the documentation.

**Comment by yecril71pl** [comment]
> it's always greatly appreciated when we get contributions

I greatly appreciate the possibility of doing useful things on my Microsoft Windows OS, and that is mainly thanks to PowerShell.  Without PowerShell this OS is good for nothing.

**Pull request merged**
