### PR TITLE
Add Gentoo PowerShell install/uninstall steps to community-support.md

### PR DESCRIPTION
**Pull request by xgqt**
# PR Summary

This PR adds Gentoo PowerShell install/uninstall instructions to `community-support.md`.

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by xgqt** [comment]
> @xgqt please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by sdwheeler** [comment]
@xqqt Thanks for the submission. However, given the complexity of maintaining this documentation we don't want to add install instructions for any/every possible Linux distribution to this article.

We could link to instructions in the Gentoo documentation. This is what we did for Arch Linux in this article. If you can provide links to the same kinds of documentation, I would welcome an update to add that information.

**Comment by xgqt** [comment]
> @xqqt Thanks for the submission. However, given the complexity of maintaining this documentation we don't want to add install instructions for any/every possible Linux distribution to this article.

This is extremely disappointing given there are instructions for Kali Linux (... a Ubuntu derivative?).

> We could link to instructions in the Gentoo documentation. This is what we did for Arch Linux in this article. If you can provide links to the same kinds of documentation, I would welcome an update to add that information.

I haven't noticed any Arch Linux information but You know, given what burden you think it is, wouldn't also checking out 3rd-party wiki be a pain?

So, summarizing, its better for Gentoo knowledge to stay on the Gentoo Wiki.
Not that its bad, but if Microsoft upstream wants it that way, so be it.

**Comment by sdwheeler** [comment]
Here is the link to the Arch Linux information in that same article: https://learn.microsoft.com/powershell/scripting/install/community-support#arch-linux.

If there are docs in the Gentoo Wiki that we can link to I would add a section for Gentoo.

**Comment by xgqt** [comment]
> If there are docs in the Gentoo Wiki that we can link to I would add a section for Gentoo.

I have just created https://wiki.gentoo.org/wiki/PowerShell

Do I have to submit a new PR or would You, @sdwheeler take care of adding a reference to it?

**Comment by sdwheeler** [comment]
@xgqt I can add it. Thanks for the quick Wiki link.

**Pull request closed without merging**
