### PR TITLE
[WIP]: Added docs for new reverse -split feature

### PR DESCRIPTION
**Pull request by ece-jacob-scott**
These are preemptive doc changes for PR (https://github.com/PowerShell/PowerShell/pull/8960).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version 6.2 of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9bde290](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/9bde290ebbe59b2fc89f0ba01e4733fac3b17919)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9bde290](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/9bde290ebbe59b2fc89f0ba01e4733fac3b17919)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 50 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9bde290](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/9bde290ebbe59b2fc89f0ba01e4733fac3b17919)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/split-operator-reverse/reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_split?view=powershell-3.0&branch=pr-en-us-3796) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/split-operator-reverse/reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C4%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903040233007888-3796%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=E7WHJ2v9rozipqyoxZEoqcj8Pq4BnPmZXy3%2FgK6cqQg%3D&st=2019-03-04T02%3A42%3A58Z&se=2019-04-04T02%3A47%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@ece-jacob-scott You are changing the v3 version of the doc. You should be changing the v6 version of the doc. Also, since this is a new feature that has not released yet, the target branch for the PR should be release-62.

**Comment by ece-jacob-scott** [comment]
@sdwheeler Sorry, I see where I went wrong now, thank you! I'll fix this soon.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[346fc49](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/346fc49e2127397e73aecbb840f2b1d0ee116add)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[346fc49](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/346fc49e2127397e73aecbb840f2b1d0ee116add)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 51 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[346fc49](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/346fc49e2127397e73aecbb840f2b1d0ee116add)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/split-operator-reverse/reference/6/Microsoft.PowerShell.Core/About/about_Split.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_split?view=powershell-6&branch=pr-en-us-3796) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/split-operator-reverse/reference/6/Microsoft.PowerShell.Core/About/about_Split.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903061713100596-3796%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3qrOuSoeW2IKttGWp619JTADhWujRpa2BxXFPX2YbsA%3D&st=2019-03-06T17%3A21%3A41Z&se=2019-04-06T17%3A26%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c3180b8](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/c3180b840598304dcfdae0bb067a56fd047fd9de)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 9 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c3180b8](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/c3180b840598304dcfdae0bb067a56fd047fd9de)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 51 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c3180b8](https://github.com/ece-jacob-scott/PowerShell-Docs/pull/3796/commits/c3180b840598304dcfdae0bb067a56fd047fd9de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/split-operator-reverse/reference/6/Microsoft.PowerShell.Core/About/about_Split.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_split?view=powershell-6&branch=pr-en-us-3796) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Split.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Split.md](https://github.com/ece-jacob-scott/PowerShell-Docs/blob/split-operator-reverse/reference/6/Microsoft.PowerShell.Core/About/about_Split.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C201903061718337921-3796%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lOHQLyQIyJ6ibZy0pDPwCR%2BZLGlAIV6lBtngitwh%2FDo%3D&st=2019-03-06T17%3A36%3A00Z&se=2019-04-06T17%3A41%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@ece-jacob-scott I hate to do this to you but the release-62 branch was totally messed up. I had to recreate it. There was no way to properly rebase it. Since your working branch was based on the old release-62 branch, it has the same problem. I renamed the broken branch to release-62-save and created a new release-62 branch with a clean history. I need to you save your changes to about_Split.md and then pull down the new release-62 branch. Create a new working branch from there, add your file back, and submit a new PR.

Sorry to give you the extra work but it is the same thing I had to do for 21 other files to get this fixed.

**Pull request closed without merging**
